/* ===== Corrective Action Register: findings, actions, verification, repeat analysis, Kaizen ===== */
const ACT_FLOW = ['Open', 'In Progress', 'Completed', 'Submitted for Verification', 'Verified', 'Closed'];
Domain.canVerify = function (a) { const u = App.user; if (!u) return false; if (u.role === 'admin') return true; const z = Domain.zone(a.zone) || {}; if (u.role === 'facilitator') return (u.apus || []).includes(a.apu); if (u.role === 'leader') return (z.leader === u.id || z.backup === u.id) && a.responsible !== u.id; return false; };
Domain.canUpdateAction = function (a) { const u = App.user; if (!u || !Domain.can('Actions', 'edit')) return false; if (['admin', 'facilitator'].includes(u.role)) return true; const z = Domain.zone(a.zone) || {}; return a.responsible === u.id || z.leader === u.id || z.backup === u.id; };
Domain.canManageFinding = function (f) { const u = App.user; if (!u || !Domain.can('Findings', 'edit')) return false; if (['admin', 'facilitator'].includes(u.role)) return true; const z = Domain.zone(f.zone) || {}; return z.leader === u.id || z.backup === u.id || (u.role === 'auditor' && f.createdBy === u.id); };

Pages.car = {
  perm: 'Findings', perm2: 'Actions',
  render(p) {
    ['tab', 'status', 'dept', 'fstatus', 'sev'].forEach((k) => { if (p[k] !== undefined) { if (k === 'tab') App.ui.carTab = p.tab; else if (['status', 'dept'].includes(k)) App.st('actF', {})[k] = p[k]; else App.st('fF', {})[k === 'fstatus' ? 'status' : k] = p[k]; delete p[k]; } });
    const u = App.user;
    const tab = App.ui.carTab || (u.role === 'member' || u.role === 'leader' ? 'actions' : 'findings');
    const fs = Domain.findings(); const acts = Domain.actions();
    const verifyQ = acts.filter((a) => a.status === 'Submitted for Verification' && Domain.canVerify(a));
    const reps = Domain.repeatGroups();
    const tabs = [['findings', 'Findings', fs.filter((f) => Domain.findSt(f) !== 'Closed').length], ['actions', 'Actions', acts.filter((a) => Domain.isActOpen(a)).length], ['verify', 'Verification', verifyQ.length], ['repeat', 'Repeat Findings', reps.length], ['kaizen', 'Improvements / Kaizen', Store.all('improvements').filter((i) => Domain.inScope(i)).length], ['gallery', 'Before / After Gallery']];
    let body = '';
    if (tab === 'findings') body = this.findings(fs);
    else if (tab === 'actions') body = this.actions(acts);
    else if (tab === 'verify') body = this.verify(verifyQ);
    else if (tab === 'repeat') body = this.repeat(reps);
    else if (tab === 'kaizen') body = this.kaizen();
    else body = this.gallery();
    return `${UI.head('Corrective Action Register', [], tab === 'kaizen' && Domain.can('Actions', 'edit') ? `<button class="btn primary" data-act="imp-edit">${icon('plus')}New improvement</button>` : `<button class="btn" data-go="reports" data-id='${JSON.stringify({ r: 'pending' })}'>${icon('file')}Pending action report</button>`, 'Finding → Corrective action → Evidence → Verification → Closure')}${UI.tabs('carTab', tabs, tab)}${body}`;
  },
  findings(all) {
    const f = App.st('fF', { status: 'open', sev: '', s: '', zone: '', apu: '', q: '' });
    const list = all.filter((x) => { const st = Domain.findSt(x); return (!f.status || (f.status === 'open' ? st !== 'Closed' : st === f.status)) && (!f.sev || x.severity === f.sev) && (!f.s || x.s === f.s) && (!f.zone || x.zone === f.zone) && (!f.apu || x.apu === f.apu) && (!f.q || (x.no + ' ' + x.desc + ' ' + x.zone).toLowerCase().includes(f.q.toLowerCase())); });
    return `<div class="filters"><input type="search" placeholder="Search finding" value="${esc(f.q)}" data-input="car-q" data-key="fF" aria-label="Search findings">${UI.sel('fF:status', [['', 'All statuses'], ['open', 'Not closed'], ['Open', 'Open (no action)'], ['In Progress', 'In progress'], ['Closed', 'Closed']], f.status)}${UI.sel('fF:sev', [['', 'All severities']].concat((Domain.masters().severities || []).map((s) => [s.name, s.name])), f.sev)}${UI.sel('fF:s', [['', 'All S']].concat(FS.S_KEYS.map((s) => [s, s + ' ' + Domain.sName(s)])), f.s)}${UI.sel('fF:apu', [['', 'All APUs']].concat((Domain.masters().apus || []).map((a) => [a.id, a.name])), f.apu)}${UI.sel('fF:zone', [['', 'All zones']].concat(Domain.scopeZones().map((z) => [z.id, z.code])), f.zone)}</div>
      ${UI.card('', UI.table('findings', [
        { k: 'no', h: 'Finding ID', r: (x) => `<b class="mono">${esc(x.no)}</b>` }, { k: 'zone', h: 'Zone', r: (x) => `<b class="mono">${esc(x.zone)}</b>` }, { k: 's', h: 'S', r: (x) => UI.stag(x.s) },
        { k: 'desc', h: 'Finding', r: (x) => `<div class="clip" style="max-width:360px">${esc(x.desc)}</div><div class="small faint clip" style="max-width:360px">${esc(x.qid)} · ${esc(x.question)}</div>` },
        { k: 'severity', h: 'Severity', r: (x) => UI.sev(x.severity) }, { k: 'ph', h: '', sortable: false, r: (x) => ((x.photos || []).length ? `<span class="faint" title="${x.photos.length} photo(s)">${icon('image').replace('<svg', '<svg style="width:16px;height:16px"')}</span>` : '') },
        { k: 'responsible', h: 'Responsible', r: (x) => esc(Domain.uname(x.responsible)), sortv: (x) => Domain.uname(x.responsible) }, { k: 'auditDate', h: 'Raised', r: (x) => fmtDate(x.auditDate) }, { k: 'due', h: 'Due', r: (x) => fmtDate(x.due) },
        { k: 'st', h: 'Status', r: (x) => UI.fBadge(x), sortv: (x) => Domain.findSt(x) }], list, { go: (x) => ['finding', x.id], sort: 'auditDate', dir: 'desc' }))}`;
  },
  actions(all) {
    const f = App.st('actF', { status: 'open', dept: '', zone: '', priority: '', mine: '', q: '' });
    const t = Domain.today;
    const list = all.filter((a) => { const st = Domain.actStatus(a); const tg = a.revisedTarget || a.target;
      if (f.status === 'open' && !Domain.isActOpen(a)) return false; if (f.status === 'due-soon' && !(['Open', 'In Progress'].includes(a.status) && tg >= t && FS.diffDays(tg, t) <= (Domain.settings().actionDueSoonDays || 3))) return false; if (f.status && !['open', 'due-soon'].includes(f.status) && st !== f.status) return false;
      return (!f.dept || a.dept === f.dept) && (!f.zone || a.zone === f.zone) && (!f.priority || a.priority === f.priority) && (!f.mine || a.responsible === App.user.id) && (!f.q || (a.no + ' ' + a.desc + ' ' + a.zone).toLowerCase().includes(f.q.toLowerCase())); });
    return `<div class="filters"><input type="search" placeholder="Search action" value="${esc(f.q)}" data-input="car-q" data-key="actF" aria-label="Search actions">${UI.sel('actF:status', [['', 'All statuses'], ['open', 'Not closed'], ['due-soon', 'Due soon']].concat(['Open', 'In Progress', 'Completed', 'Submitted for Verification', 'Verified', 'Rejected', 'Overdue', 'Closed'].map((s) => [s, s])), f.status)}${UI.sel('actF:dept', [['', 'All departments']].concat((Domain.masters().departments || []).map((d) => [d.name, d.name])), f.dept)}${UI.sel('actF:zone', [['', 'All zones']].concat(Domain.scopeZones().map((z) => [z.id, z.code])), f.zone)}${UI.sel('actF:priority', [['', 'All priorities']].concat((Domain.masters().priorities || []).map((p) => [p, p])), f.priority)}${UI.sel('actF:mine', [['', 'Everyone'], ['1', 'Assigned to me']], f.mine)}</div>
      ${UI.card('', UI.table('actions', [
        { k: 'no', h: 'Action ID', r: (a) => `<b class="mono">${esc(a.no)}</b><div class="small faint mono">${esc(a.findingNo || '')}</div>` }, { k: 'zone', h: 'Zone', r: (a) => `<b class="mono">${esc(a.zone)}</b>` },
        { k: 'desc', h: 'Action', r: (a) => `<div class="clip" style="max-width:340px">${esc(a.desc)}</div><div class="small faint">${esc(a.type)}</div>` },
        { k: 'responsible', h: 'Responsible', r: (a) => UI.person(a.responsible), sortv: (a) => Domain.uname(a.responsible) }, { k: 'dept', h: 'Department' },
        { k: 'priority', h: 'Priority', r: (a) => UI.badge(a.priority, a.priority === 'High' ? 'b-red' : a.priority === 'Medium' ? 'b-amber' : 'b-gray') },
        { k: 'target', h: 'Target', r: (a) => `${fmtDate(a.revisedTarget || a.target)}${a.revisedTarget ? '<div class="tiny faint">revised</div>' : ''}`, sortv: (a) => a.revisedTarget || a.target },
        { k: 'st', h: 'Status', r: (a) => UI.actBadge(a), sortv: (a) => Domain.actStatus(a) }], list, { go: (a) => ['action', a.id], sort: 'target', rowCls: (a) => (Domain.actStatus(a) === 'Overdue' ? 'over' : '') }))}`;
  },
  verify(q) {
    if (!q.length) return UI.card('', UI.empty('check', 'Nothing waiting for your verification', 'Actions appear here when the responsible person submits evidence.'));
    return `<div class="stack">${q.map((a) => { const f = Store.get('findings', a.findingId) || {}; return `<div class="card"><div class="card-b"><div class="row between top"><div><div class="mono small faint">${esc(a.no)} · ${esc(f.no || '')} · ${esc(a.zone)}</div><h3>${esc(a.desc)}</h3><div class="small muted">${esc(f.desc || '')}</div><div class="small" style="margin-top:4px">${UI.person(a.responsible)} · submitted ${fmtDT(a.submittedAt)}</div></div><div class="row">${UI.sev(f.severity || '')}<button class="btn primary" data-go="action" data-id="${a.id}">Verify</button></div></div><div class="ba-imgs" style="margin-top:12px;border-radius:8px;overflow:hidden;max-width:520px"><figure>${(f.photos || [])[0] ? `<img src="${f.photos[0].thumb}" alt="Before" data-act="lightbox" data-ref="${attr(f.photos[0])}">` : '<div class="empty small" style="padding:20px">No before photo</div>'}<figcaption>BEFORE</figcaption></figure><figure class="after">${(a.evidence || [])[0] ? `<img src="${a.evidence[0].thumb}" alt="After" data-act="lightbox" data-ref="${attr(a.evidence[0])}">` : '<div class="empty small" style="padding:20px">No evidence photo</div>'}<figcaption>AFTER</figcaption></figure></div></div></div>`; }).join('')}</div>`;
  },
  repeat(reps) {
    if (!reps.length) return UI.card('', UI.empty('repeat', 'No repeat findings', 'A finding repeats when the same checkpoint fails in the same zone in more than one audit.'));
    return `<div class="stack">${reps.map((r) => { const z = Domain.zone(r.zone) || {}; return `<div class="card"><div class="card-b"><div class="banner hazard" style="margin-bottom:12px"><div class="grow"><div class="eyebrow">Repeat finding alert</div><div style="font:600 17px var(--f-display);margin-top:2px">Zone ${esc(z.code)} · ${r.s} – ${esc(Domain.sName(r.s))}</div><div>${esc(r.desc)}</div><div class="small muted">${r.consecutive >= 2 ? `Found in ${r.consecutive} consecutive audits` : `Found in ${r.count} audits`}</div></div><span class="score lg" style="background:${r.consecutive >= 3 ? 'var(--bad)' : 'var(--warn)'}">${r.count}×</span></div>
      ${UI.kv([['First occurrence', fmtDate(r.first)], ['Last occurrence', fmtDate(r.last)], ['No. of occurrences', String(r.count)], ['Question', `<span class="mono">${esc(r.qid)}</span> ${esc(r.question)}`], ['Responsible person', esc(Domain.uname(r.responsible))], ['Effectiveness status', `<span style="color:${/Not effective/.test(r.effectiveness) ? 'var(--bad)' : 'var(--warn)'}">${esc(r.effectiveness)}</span>`], ['Previous corrective action', esc(r.prevAction || '—')]])}
      <div class="divider" style="margin:12px 0"></div><div class="row tight">${r.findings.map((f) => `<button class="chip" data-go="finding" data-id="${f.id}"><span class="mono">${esc(f.no)}</span> ${fmtDate(f.auditDate)} ${UI.fBadge(f)}</button>`).join('')}</div></div></div>`; }).join('')}</div>`;
  },
  kaizen() {
    const list = Store.all('improvements').filter((i) => Domain.inScope(i));
    const total = sum(list.map((i) => i.saving));
    return `<div class="kpis" style="margin-bottom:14px"><div class="kpi"><span class="k-l">Improvements</span><span class="k-v">${list.length}</span></div><div class="kpi"><span class="k-l">Implemented or closed</span><span class="k-v">${list.filter((i) => ['Implemented', 'Verified', 'Closed'].includes(i.status)).length}</span></div><div class="kpi"><span class="k-l">Cost saving</span><span class="k-v">₹${(total / 100000).toFixed(2)}<small> lakh</small></span></div><div class="kpi"><span class="k-l">Linked to findings</span><span class="k-v">${list.filter((i) => i.findingId).length}</span></div></div>
      ${UI.card('', UI.table('kaizen', [{ k: 'no', h: 'Improvement ID', r: (i) => `<b class="mono">${esc(i.no)}</b>` }, { k: 'zone', h: 'Zone', r: (i) => `<b class="mono">${esc(i.zone)}</b>` }, { k: 's', h: 'S', r: (i) => (i.s ? UI.stag(i.s) : '') }, { k: 'title', h: 'Improvement', r: (i) => `<b>${esc(i.title)}</b><div class="small muted clip" style="max-width:360px">${esc(i.idea)}</div>` }, { k: 'benefits', h: 'Benefit', r: (i) => (i.benefits || []).map((b) => `<span class="chip" style="margin:1px">${esc(b)}</span>`).join('') }, { k: 'saving', h: 'Saving (₹)', num: true, r: (i) => (i.saving ? Number(i.saving).toLocaleString('en-IN') : '—') }, { k: 'owner', h: 'Owner', r: (i) => esc(Domain.uname(i.owner)) }, { k: 'date', h: 'Date', r: (i) => fmtDate(i.date) }, { k: 'status', h: 'Status', r: (i) => UI.badge(i.status, { Idea: 'b-blue', 'In Progress': 'b-indigo', Implemented: 'b-teal', Verified: 'b-green', Closed: 'b-gray' }[i.status]) }], list, { go: (i) => ['improvement', i.id], sort: 'date', dir: 'desc' }))}`;
  },
  baCard(i) { const z = Domain.zone(i.zone) || {}; return `<div class="ba"><div class="ba-imgs"><figure>${i.beforePhoto ? `<img src="${i.beforePhoto.thumb}" alt="Before" data-act="lightbox" data-ref="${attr(i.beforePhoto)}">` : ''}<figcaption>BEFORE</figcaption></figure><figure class="after">${i.afterPhoto ? `<img src="${i.afterPhoto.thumb}" alt="After" data-act="lightbox" data-ref="${attr(i.afterPhoto)}">` : '<div class="empty small" style="padding:30px 6px">After photo pending</div>'}<figcaption>AFTER</figcaption></figure></div><div class="ba-b"><div class="row between"><span class="mono small faint">${esc(i.no || '')} · ${esc(z.code || i.zone)}</span>${i.s ? UI.stag(i.s) : ''}</div><b style="font-family:var(--f-display);font-size:16px">${esc(i.title)}</b><div class="small muted">${esc(i.after || i.idea || '')}</div><div class="row between small"><span>${UI.person(i.owner)}</span><span class="faint">${fmtDate(i.date)}</span></div>${i.id && i.id.startsWith('IMP') ? `<button class="btn sm" data-go="improvement" data-id="${i.id}">Open</button>` : i.actionId ? `<button class="btn sm" data-go="action" data-id="${i.actionId}">Open action</button>` : ''}</div></div>`; },
  gallery() {
    const imps = Store.all('improvements').filter((i) => Domain.inScope(i) && i.beforePhoto);
    const acts = Domain.actions().filter((a) => ['Verified', 'Closed'].includes(a.status) && (a.evidence || []).length).map((a) => { const f = Store.get('findings', a.findingId) || {}; return (f.photos || []).length ? { title: a.desc, zone: a.zone, s: f.s, beforePhoto: f.photos[0], afterPhoto: a.evidence[0], owner: a.responsible, date: (a.verifiedAt || '').slice(0, 10), after: f.desc, no: a.no, actionId: a.id } : null; }).filter(Boolean).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 24);
    return `<h3 style="margin-bottom:10px">Kaizen improvements</h3><div class="gallery">${imps.map(this.baCard).join('') || UI.empty('image', 'No improvements with photos yet')}</div><h3 style="margin:24px 0 10px">Verified corrective actions</h3><div class="gallery">${acts.map(this.baCard).join('') || UI.empty('image', 'No verified actions with before/after photos yet')}</div>`;
  },
};
Acts['car-q'] = (el) => { App.st(el.dataset.key, {}).q = el.value; clearTimeout(Acts._cq); Acts._cq = setTimeout(() => { App.render(); const i = $(`[data-input="car-q"]`); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } }, 300); };

/* ---------- Finding detail ---------- */
Pages.finding = {
  perm: 'Findings', perm2: 'Actions',
  render(p) {
    const f = Store.get('findings', p.id); if (!f) return UI.empty('flag', 'Finding not found');
    const w = Store.get('workorders', f.woId); const acts = Store.all('actions').filter((a) => a.findingId === f.id); const st = Domain.findSt(f);
    const rep = Domain.repeatGroups(Store.all('findings').filter((x) => x.zone === f.zone)).find((r) => r.qid === f.qid);
    const can = Domain.canManageFinding(f);
    const btns = can ? `${st !== 'Closed' ? `<button class="btn primary" data-act="act-new" data-id="${f.id}">${icon('plus')}Assign action</button>` : ''}<button class="btn" data-act="f-edit" data-id="${f.id}">${icon('edit')}Edit</button><button class="btn" data-act="imp-edit" data-finding="${f.id}">${icon('bulb')}Convert to Kaizen</button>${st !== 'Closed' && !acts.length && ['Observation', 'Improvement Opportunity'].includes(f.severity) ? `<button class="btn" data-act="f-close" data-id="${f.id}">${icon('check')}Close without action</button>` : ''}` : '';
    return `${UI.head(`Finding <span class="mono" style="font-size:.72em">${esc(f.no)}</span>`, [['Corrective Action Register', 'car'], f.no], btns, `${UI.fBadge(f)} ${UI.sev(f.severity)} · ${UI.stag(f.s)} ${esc(Domain.sName(f.s))}`)}
      ${rep ? `<div class="banner hazard"><div class="grow"><b>Repeat finding</b> – this checkpoint failed in ${rep.count} audits${rep.consecutive >= 2 ? ` (${rep.consecutive} consecutive)` : ''}. ${esc(rep.effectiveness)}.</div><button class="btn sm" data-go="car" data-id='${JSON.stringify({ tab: 'repeat' })}'>Repeat analysis</button></div>` : ''}
      <div class="grid"><div class="c8"><div class="stack loose">${UI.card(esc(f.desc), UI.kv([['Finding ID', `<span class="mono">${esc(f.no)}</span>`], ['Audit', w ? UI.link('wo', w.id, w.no) : esc(f.woNo)], ['Work order ID', `<span class="mono">${esc(f.woId)}</span>`], ['Zone', `${UI.link('zone', f.zone, f.zone)} ${esc((Domain.zone(f.zone) || {}).name || '')}`], ['APU / Department', `${esc(Domain.apuName(f.apu))} · ${esc(f.dept)}`], ['S category', `${UI.stag(f.s)} ${esc(Domain.sName(f.s))}`], ['Question', `<span class="mono">${esc(f.qid)}</span> ${esc(f.question)}`], ['Score given', f.score ?? '—'], ['Finding category', esc(f.category)], ['Severity', UI.sev(f.severity)], ['Responsible person', UI.person(f.responsible)], ['Due date', fmtDate(f.due)], ['Raised by', esc(Domain.uname(f.createdBy))], ['Raised on', fmtDT(f.createdAt)], ['Immediate action', esc(f.immediate)], ['Root cause', esc(f.rootCause)], ['Corrective action', esc(f.ca)], ['Preventive action', esc(f.pa)]]))}
        ${UI.card('Corrective actions', acts.length ? `<div class="stack">${acts.map((a) => `<div class="row between" style="padding:8px 0;border-bottom:1px solid var(--line-2)"><div class="grow"><div class="row tight"><b class="mono">${esc(a.no)}</b><span class="small faint">${esc(a.type)}</span></div><div>${esc(a.desc)}</div><div class="small muted">${esc(Domain.uname(a.responsible))} · target ${fmtDate(a.revisedTarget || a.target)}</div></div><div class="row">${UI.actBadge(a)}<button class="btn sm" data-go="action" data-id="${a.id}">Open</button></div></div>`).join('')}</div>` : UI.empty('wrench', 'No actions assigned yet', can ? 'Assign a corrective action to start the closure workflow.' : ''))}</div></div>
      <div class="c4"><div class="stack loose">${UI.card('Evidence photographs', UI.thumbs(f.photos, { lg: true, empty: '<div class="faint small">No photographs</div>' }) + (can ? `<button class="btn sm" style="margin-top:10px" data-act="f-photo" data-id="${f.id}">${icon('camera')}Add photo</button>` : ''))}
        ${rep ? UI.card('Occurrences of this checkpoint', `<div class="tl">${rep.findings.slice().reverse().map((x) => `<div class="tl-i"><span class="tl-dot" style="background:${x.id === f.id ? 'var(--bad)' : 'var(--ink-3)'}"></span><div><div class="t">${UI.link('finding', x.id, x.no)} · ${fmtDate(x.auditDate)}</div><div class="w">${esc(x.desc)} · ${Domain.findSt(x)}</div></div></div>`).join('')}</div>`) : ''}</div></div></div>`;
  },
};
Object.assign(Acts, {
  'f-edit'(el) {
    const f = Store.get('findings', el.dataset.id); const z = Domain.zone(f.zone) || {}; const team = uniq([z.leader, z.backup].concat(z.members || [])).filter(Boolean);
    const fields = [{ name: 'desc', label: 'Finding description', type: 'textarea', required: true, full: true }, { name: 'severity', label: 'Severity', type: 'select', options: (Domain.masters().severities || []).map((s) => s.name), required: true }, { name: 'category', label: 'Category', type: 'select', options: Domain.masters().findingCategories || [] }, { name: 'responsible', label: 'Responsible person', type: 'select', options: team.map((id) => [id, Domain.uname(id)]), required: true }, { name: 'due', label: 'Due date', type: 'date', required: true, validate: (v) => (v < f.auditDate ? 'Due date cannot be before the audit date' : '') }, { name: 'immediate', label: 'Immediate action', full: true }, { name: 'rootCause', label: 'Root cause', type: 'textarea', full: true }, { name: 'ca', label: 'Corrective action', type: 'textarea' }, { name: 'pa', label: 'Preventive action', type: 'textarea' }];
    UI.modal({ title: 'Edit finding', sub: f.no, size: 'wide', body: UI.form(fields, f), actions: [{ label: 'Cancel' }, { label: 'Save', cls: 'primary', onClick: async (m) => { const v = UI.readForm(m, fields); if (!v) return false; const ch = Object.keys(v).filter((k) => String(v[k] ?? '') !== String(f[k] ?? '')); await Store.patch('findings', f.id, Object.assign(v, { updatedAt: nowISO(), updatedBy: App.user.id })); Domain.log('Findings', f.no, 'Finding updated', ch.map((k) => `${k}: ${f[k] ?? ''}`).join('; '), ch.map((k) => `${k}: ${v[k] ?? ''}`).join('; ')); if (v.responsible !== f.responsible) Domain.log('Findings', f.no, 'Finding reassigned', Domain.uname(f.responsible), Domain.uname(v.responsible)); } }] });
  },
  async 'f-close'(el) { const f = Store.get('findings', el.dataset.id); if (!(await UI.confirm('Close finding?', 'Close this observation without a corrective action?', 'Close finding'))) return; await Store.patch('findings', f.id, { status: 'Closed', closedAt: nowISO(), closedBy: App.user.id }); Domain.log('Findings', f.no, 'Finding closed', 'Open', 'Closed (no action required)'); },
  async 'f-photo'(el) { const f = Store.get('findings', el.dataset.id); const refs = await UI.capture({ findingId: f.id, zone: f.zone, kind: 'before' }, { capture: false }); if (refs.length) { await Store.patch('findings', f.id, { photos: (f.photos || []).concat(refs) }); Domain.log('Findings', f.no, 'Photo added'); } },
  'act-new'(el) {
    const f = Store.get('findings', el.dataset.id); const z = Domain.zone(f.zone) || {}; const st = Domain.settings();
    const people = UI.userOpts((u) => (u.apus || []).includes(f.apu) || u.role === 'admin');
    const fields = [{ name: 'desc', label: 'Action description', type: 'textarea', required: true, full: true }, { name: 'type', label: 'Action type', type: 'select', options: Domain.masters().actionTypes || ['Corrective', 'Preventive', 'Improvement'], required: true, value: 'Corrective' }, { name: 'priority', label: 'Priority', type: 'select', options: Domain.masters().priorities || [], required: true, value: ['Critical', 'Major'].includes(f.severity) ? 'High' : 'Medium' }, { name: 'responsible', label: 'Responsible person', type: 'select', options: people, required: true, value: f.responsible }, { name: 'dept', label: 'Department', type: 'select', options: (Domain.masters().departments || []).map((d) => d.name), required: true, value: f.dept }, { name: 'target', label: 'Target date', type: 'date', required: true, value: f.due || FS.addDays(Domain.today, (st.ncClosure || {})[f.severity] || 15), validate: (v) => (v < f.auditDate ? 'Target date cannot be before the audit date' : '') }, { name: 'rootCause', label: 'Root cause (if known)', type: 'textarea', full: true }];
    UI.modal({ title: 'Assign corrective action', sub: `${f.no} · ${f.desc}`, size: 'wide', body: UI.form(fields), actions: [{ label: 'Cancel' }, { label: 'Assign action', cls: 'primary', onClick: async (m) => {
      const v = UI.readForm(m, fields); if (!v) return false; const n = await Store.nextNo('ACT');
      await Store.put('actions', n.id, Object.assign(v, { no: n.no, findingId: f.id, findingNo: f.no, woId: f.woId, zone: f.zone, plant: f.plant, apu: f.apu, status: 'Open', ca: '', pa: '', evidence: [], createdAt: nowISO(), createdBy: App.user.id, history: [{ at: nowISO(), by: App.user.id, from: '', to: 'Open', note: 'Action assigned' }] }));
      Domain.notify('Action assigned', 'Action assigned: ' + n.no, v.desc, [v.responsible], { page: 'action', id: n.id }); Domain.log('Actions', n.no, 'Action created', '', `${f.no} → ${Domain.uname(v.responsible)}`);
      UI.toast('Action assigned to ' + Domain.uname(v.responsible), 'good'); } }] });
  },
});

/* ---------- Action detail ---------- */
Pages.action = {
  perm: 'Actions', perm2: 'Findings',
  render(p) {
    const a = Store.get('actions', p.id); if (!a) return UI.empty('wrench', 'Action not found');
    const f = Store.get('findings', a.findingId) || {}; const st = Domain.actStatus(a);
    const canU = Domain.canUpdateAction(a) && Domain.isActOpen(a) && a.status !== 'Submitted for Verification';
    const canV = a.status === 'Submitted for Verification' && Domain.canVerify(a);
    const canClose = a.status === 'Verified' && (Domain.canVerify(a) || App.user.role === 'facilitator');
    const canMng = ['admin', 'facilitator'].includes(App.user.role) || (Domain.zone(a.zone) || {}).leader === App.user.id;
    const flowIdx = ACT_FLOW.indexOf(a.status === 'Rejected' ? 'In Progress' : a.status);
    const btns = [canU ? `<button class="btn primary" data-act="act-update" data-id="${a.id}">${icon('edit')}Update progress</button>` : '', canMng && Domain.isActOpen(a) ? `<button class="btn" data-act="act-reassign" data-id="${a.id}">${icon('users')}Reassign</button>` : '', canClose ? `<button class="btn good" data-act="act-close" data-id="${a.id}">${icon('lock')}Close action</button>` : ''].join('');
    return `${UI.head(`Action <span class="mono" style="font-size:.72em">${esc(a.no)}</span>`, [['Corrective Action Register', 'car'], [f.no || 'Finding', 'finding', f.id], a.no], btns, `${UI.actBadge(a)} · ${esc(a.type)} · ${esc(a.priority)} priority`)}
      ${a.status === 'Rejected' ? `<div class="banner warn">${icon('x')}<div><b>Rework required</b> – ${esc(a.rejectReason || '')}${a.revisedTarget ? ` · revised target ${fmtDate(a.revisedTarget)}` : ''}</div></div>` : ''}
      ${st === 'Overdue' ? `<div class="banner hazard">${icon('clock')}<span>Target date ${fmtDate(a.revisedTarget || a.target)} has passed (${-FS.diffDays(a.revisedTarget || a.target, Domain.today)} days overdue).</span></div>` : ''}
      <div class="card" style="margin-bottom:16px"><div class="card-b"><div class="steps">${ACT_FLOW.map((s, i) => `<div class="step ${i < flowIdx || (i === flowIdx && ['Verified', 'Closed'].includes(a.status)) ? 'done' : i === flowIdx ? (a.status === 'Rejected' ? 'bad cur' : 'cur') : ''}"><i></i>${esc(s)}</div>`).join('')}</div></div></div>
      ${canV ? Pages.action.verifyPanel(a, f) : ''}
      <div class="grid"><div class="c8"><div class="stack loose">${UI.card(esc(a.desc), UI.kv([['Action ID', `<span class="mono">${esc(a.no)}</span>`], ['Finding', f.id ? UI.link('finding', f.id, f.no) : '—'], ['Zone', UI.link('zone', a.zone, a.zone)], ['Department', esc(a.dept)], ['Responsible person', UI.person(a.responsible)], ['Target date', fmtDate(a.target)], ['Revised target', a.revisedTarget ? fmtDate(a.revisedTarget) : ''], ['Priority', esc(a.priority)], ['Root cause', esc(a.rootCause)], ['Corrective action', esc(a.ca)], ['Preventive action', esc(a.pa)], ['Completion date', fmtDate(a.completedAt)], ['Verification by', esc(a.verifiedBy ? Domain.uname(a.verifiedBy) : '')], ['Verification date', a.verifiedAt ? fmtDT(a.verifiedAt) : ''], ['Verification remarks', esc(a.verRemarks || '')], ['Created', `${fmtDT(a.createdAt)} by ${esc(Domain.uname(a.createdBy))}`]]))}
        ${UI.card('History', `<div class="tl">${(a.history || []).slice().reverse().map((h) => `<div class="tl-i"><span class="tl-dot" style="background:${h.to === 'Rejected' ? 'var(--bad)' : ['Verified', 'Closed'].includes(h.to) ? 'var(--good)' : 'var(--accent)'}"></span><div><div class="t">${h.from ? esc(h.from) + ' → ' : ''}<b>${esc(h.to)}</b>${h.note ? ' – ' + esc(h.note) : ''}</div><div class="w">${fmtDT(h.at)} · ${esc(Domain.uname(h.by))}</div></div></div>`).join('')}</div>`)}</div></div>
      <div class="c4"><div class="stack loose">${UI.card('Finding', `<div>${esc(f.desc || '')}</div><div class="small muted" style="margin:4px 0 10px">${UI.sev(f.severity || '')} · ${UI.stag(f.s || 'S1')} ${esc(f.question || '')}</div><div class="eyebrow" style="margin-bottom:6px">Original photograph</div>${UI.thumbs(f.photos, { lg: true, empty: '<div class="small faint">None</div>' })}`)}${UI.card('Completion evidence', UI.thumbs(a.evidence, { lg: true, empty: '<div class="small faint">No evidence uploaded yet</div>' }) + (canU ? `<button class="btn sm" style="margin-top:10px" data-act="act-evidence" data-id="${a.id}">${icon('camera')}Upload evidence</button>` : ''))}</div></div></div>`;
  },
  verifyPanel(a, f) {
    return `<div class="card" style="margin-bottom:16px;border-color:var(--warn)"><div class="card-h"><div><h3>Verify action effectiveness</h3><div class="sub">Compare the original condition with the completion evidence, then accept or send back for rework.</div></div></div><div class="card-b"><div class="grid"><div class="c6"><div class="ba-imgs" style="border-radius:8px;overflow:hidden"><figure>${(f.photos || [])[0] ? `<img src="${f.photos[0].thumb}" alt="Before" data-act="lightbox" data-ref="${attr(f.photos[0])}">` : '<div class="empty small" style="padding:30px 4px">No original photo</div>'}<figcaption>BEFORE</figcaption></figure><figure class="after">${(a.evidence || [])[0] ? `<img src="${a.evidence[0].thumb}" alt="After" data-act="lightbox" data-ref="${attr(a.evidence[0])}">` : '<div class="empty small" style="padding:30px 4px">No completion photo</div>'}<figcaption>AFTER</figcaption></figure></div></div>
      <div class="c6 stack">${UI.kv([['Corrective action', esc(a.ca || a.desc)], ['Responsible', esc(Domain.uname(a.responsible))], ['Completion date', fmtDate(a.completedAt)], ['Preventive action', esc(a.pa)]])}<div class="row" style="justify-content:flex-end;margin-top:auto"><button class="btn danger" data-act="act-reject" data-id="${a.id}">${icon('x')}Reject / Rework</button><button class="btn good" data-act="act-accept" data-id="${a.id}">${icon('check')}Accept</button></div></div></div></div></div>`;
  },
};
const actStep = async (a, to, extra = {}, note = '') => {
  const h = (a.history || []).concat([{ at: nowISO(), by: App.user.id, from: a.status, to, note }]);
  await Store.patch('actions', a.id, Object.assign({ status: to, history: h }, extra));
  Domain.log('Actions', a.no, 'Status changed', a.status, to + (note ? ' – ' + note : ''));
  const f = Store.get('findings', a.findingId); if (f) { const acts = Store.all('actions').filter((x) => x.findingId === f.id); const ns = acts.length && acts.every((x) => FS.ACT_CLOSED.includes(x.status)) ? 'Closed' : 'In Progress'; if (f.status !== ns) Store.patch('findings', f.id, { status: ns }); }
};
Object.assign(Acts, {
  'act-update'(el) {
    const a = Store.get('actions', el.dataset.id);
    const fields = [{ name: 'status', label: 'Status', type: 'select', options: ['Open', 'In Progress', 'Completed'], required: true, blank: false }, { name: 'completedAt', label: 'Completion date', type: 'date', validate: (v, o) => (o.status === 'Completed' && !v ? 'Enter the completion date' : v && v > Domain.today ? 'Completion date cannot be in the future' : '') }, { name: 'rootCause', label: 'Root cause', type: 'textarea', full: true }, { name: 'ca', label: 'Corrective action taken', type: 'textarea', full: true }, { name: 'pa', label: 'Preventive action', type: 'textarea', full: true }, { name: 'submit', label: 'Submit for verification now (evidence required)', type: 'checkbox', full: true }];
    UI.modal({ title: 'Update action', sub: `${a.no} · ${a.desc}`, size: 'wide', body: UI.form(fields, Object.assign({}, a, { status: a.status === 'Rejected' ? 'In Progress' : a.status, completedAt: a.completedAt || (a.status === 'Completed' ? Domain.today : '') })) + `<div class="divider" style="margin:14px 0"></div><div class="eyebrow" style="margin-bottom:6px">Evidence</div><div id="ev-thumbs">${UI.thumbs(a.evidence, { empty: '<div class="small faint">No evidence yet</div>' })}</div><button class="btn sm" style="margin-top:8px" data-act="act-evidence" data-id="${a.id}" data-inmodal="1">${icon('camera')}Add evidence photo</button>`,
      actions: [{ label: 'Cancel' }, { label: 'Save', cls: 'primary', onClick: async (m) => {
        const v = UI.readForm(m, fields); if (!v) return false; const cur = Store.get('actions', a.id);
        if (v.submit) { if (!(cur.evidence || []).length) { UI.toast('Upload at least one evidence photo before submitting for verification', 'bad'); return false; } if (!v.ca) { UI.toast('Describe the corrective action taken', 'bad'); return false; } }
        const extra = { rootCause: v.rootCause, ca: v.ca, pa: v.pa, completedAt: v.completedAt || (v.submit ? Domain.today : cur.completedAt || '') };
        if (v.submit) { await actStep(cur, 'Submitted for Verification', Object.assign(extra, { submittedAt: nowISO() }), 'Evidence submitted'); const z = Domain.zone(a.zone) || {}; Domain.notify('Action submitted', 'Action submitted for verification: ' + a.no, a.desc, [z.leader, Domain.facilitatorOf(a.apu)].filter((x) => x !== App.user.id), { page: 'action', id: a.id }); UI.toast('Submitted for verification', 'good'); }
        else if (v.status !== cur.status) await actStep(cur, v.status, extra);
        else { await Store.patch('actions', a.id, extra); Domain.log('Actions', a.no, 'Action updated'); }
        const f = Store.get('findings', a.findingId); if (f && (v.rootCause || v.ca || v.pa)) Store.patch('findings', f.id, { rootCause: f.rootCause || v.rootCause, ca: f.ca || v.ca, pa: f.pa || v.pa });
      } }] });
  },
  async 'act-evidence'(el) {
    const a = Store.get('actions', el.dataset.id); const refs = await UI.capture({ actionId: a.id, findingId: a.findingId, zone: a.zone, kind: 'after' }, { capture: false });
    if (!refs.length) return; const ev = (Store.get('actions', a.id).evidence || []).concat(refs); await Store.patch('actions', a.id, { evidence: ev }); Domain.log('Actions', a.no, 'Evidence uploaded', '', refs.length + ' photo(s)');
    const box = $('#ev-thumbs'); if (box) box.innerHTML = UI.thumbs(ev); UI.toast('Evidence uploaded', 'good');
  },
  'act-accept'(el) {
    const a = Store.get('actions', el.dataset.id); const fields = [{ name: 'verRemarks', label: 'Verification remarks', type: 'textarea', full: true, value: 'Effective – verified on the shop floor' }, { name: 'close', label: 'Close the action now', type: 'checkbox', value: true, full: true }];
    UI.modal({ title: 'Accept action', sub: a.no, body: UI.form(fields), actions: [{ label: 'Cancel' }, { label: 'Accept', cls: 'good', onClick: async (m) => { const v = UI.readForm(m, fields); await actStep(a, 'Verified', { verifiedBy: App.user.id, verifiedAt: nowISO(), verRemarks: v.verRemarks || 'Verified' }, v.verRemarks); if (v.close) await actStep(Store.get('actions', a.id), 'Closed', { closedAt: nowISO() }); Domain.notify(v.close ? 'Action closed' : 'Action verified', `Action ${v.close ? 'closed' : 'verified'}: ${a.no}`, v.verRemarks, [a.responsible], { page: 'action', id: a.id }); UI.toast(v.close ? 'Action verified and closed' : 'Action verified', 'good'); } }] });
  },
  'act-reject'(el) {
    const a = Store.get('actions', el.dataset.id); const fields = [{ name: 'reason', label: 'Rejection reason', type: 'textarea', required: true, full: true }, { name: 'revisedTarget', label: 'Revised target date', type: 'date', required: true, value: FS.addDays(Domain.today, 7), validate: (v) => (v < Domain.today ? 'Revised target must be today or later' : '') }, { name: 'remarks', label: 'Additional remarks', full: true }];
    UI.modal({ title: 'Reject – rework required', sub: a.no, body: UI.form(fields), actions: [{ label: 'Cancel' }, { label: 'Reject action', cls: 'danger solid', onClick: async (m) => { const v = UI.readForm(m, fields); if (!v) return false; await actStep(a, 'Rejected', { rejectReason: v.reason + (v.remarks ? ' – ' + v.remarks : ''), revisedTarget: v.revisedTarget, verRemarks: v.reason, rejections: (a.rejections || 0) + 1 }, v.reason); Domain.notify('Action rejected', 'Action needs rework: ' + a.no, v.reason, [a.responsible], { page: 'action', id: a.id }); } }] });
  },
  async 'act-close'(el) { const a = Store.get('actions', el.dataset.id); if (a.status !== 'Verified') { UI.toast('An action must be verified before it can be closed', 'bad'); return; } await actStep(a, 'Closed', { closedAt: nowISO() }); Domain.notify('Action closed', 'Action closed: ' + a.no, a.desc, [a.responsible], { page: 'action', id: a.id }); UI.toast('Action closed', 'good'); },
  'act-reassign'(el) {
    const a = Store.get('actions', el.dataset.id); const fields = [{ name: 'responsible', label: 'New responsible person', type: 'select', options: UI.userOpts((u) => (u.apus || []).includes(a.apu)), required: true }, { name: 'target', label: 'Target date', type: 'date', required: true }, { name: 'reason', label: 'Reason', required: true, full: true }];
    UI.modal({ title: 'Reassign action', sub: a.no, body: UI.form(fields, { responsible: a.responsible, target: a.revisedTarget || a.target }), actions: [{ label: 'Cancel' }, { label: 'Reassign', cls: 'primary', onClick: async (m) => { const v = UI.readForm(m, fields); if (!v) return false; await Store.patch('actions', a.id, { responsible: v.responsible, revisedTarget: v.target !== a.target ? v.target : a.revisedTarget || '', history: (a.history || []).concat([{ at: nowISO(), by: App.user.id, from: a.status, to: a.status, note: `Reassigned to ${Domain.uname(v.responsible)}: ${v.reason}` }]) }); Domain.log('Actions', a.no, 'Action reassigned', Domain.uname(a.responsible), Domain.uname(v.responsible)); Domain.notify('Action assigned', 'Action assigned: ' + a.no, a.desc, [v.responsible], { page: 'action', id: a.id }); } }] });
  },
});

/* ---------- Improvement / Kaizen ---------- */
Pages.improvement = {
  perm: 'Actions', perm2: 'Findings',
  render(p) {
    const i = Store.get('improvements', p.id); if (!i) return UI.empty('bulb', 'Improvement not found');
    const can = Domain.can('Actions', 'edit'); const flow = ['Idea', 'In Progress', 'Implemented', 'Verified', 'Closed']; const idx = flow.indexOf(i.status);
    return `${UI.head(esc(i.title), [['Corrective Action Register', 'car'], 'Kaizen', i.no], can ? `<button class="btn" data-act="imp-edit" data-id="${i.id}">${icon('edit')}Edit</button>${i.status === 'Implemented' && ['admin', 'facilitator', 'leader'].includes(App.user.role) ? `<button class="btn good" data-act="imp-verify" data-id="${i.id}">${icon('check')}Verify benefit</button>` : ''}` : '', `<span class="mono">${esc(i.no)}</span> · ${esc(i.zone)} · ${UI.badge(i.status, 'b-teal')}`)}
      <div class="card" style="margin-bottom:16px"><div class="card-b"><div class="steps">${['5S Finding', 'Improvement Action', 'Kaizen', 'Before / After', 'Benefit', 'Verification', 'Closure'].map((s, k) => `<div class="step ${k <= Math.min(6, idx + 2) ? 'done' : ''}"><i></i>${s}</div>`).join('')}</div></div></div>
      <div class="grid"><div class="c7">${Pages.car.baCard(Object.assign({}, i, { id: '' }))}</div><div class="c5">${UI.card('Details', UI.kv([['Improvement ID', `<span class="mono">${esc(i.no)}</span>`], ['Zone', UI.link('zone', i.zone, i.zone)], ['Linked finding', i.findingId ? UI.link('finding', i.findingId, (Store.get('findings', i.findingId) || {}).no || i.findingId) : ''], ['Before condition', esc(i.before)], ['Improvement idea', esc(i.idea)], ['Description', esc(i.desc)], ['After condition', esc(i.after)], ['Owner', UI.person(i.owner)], ['Date', fmtDate(i.date)], ['Benefits', (i.benefits || []).map((b) => `<span class="chip" style="margin:1px">${esc(b)}</span>`).join('')], ['Cost saving', i.saving ? '₹' + Number(i.saving).toLocaleString('en-IN') : ''], ['Verified by', esc(i.verifiedBy ? Domain.uname(i.verifiedBy) : '')]]))}</div></div>`;
  },
};
Object.assign(Acts, {
  'imp-edit'(el) {
    const i0 = el.dataset.id ? Store.get('improvements', el.dataset.id) : null; const fnd = el.dataset.finding ? Store.get('findings', el.dataset.finding) : null; const ms = Domain.masters();
    const init = i0 || (fnd ? { zone: fnd.zone, s: fnd.s, findingId: fnd.id, title: 'Kaizen: ' + fnd.desc, before: fnd.desc, owner: fnd.responsible, date: Domain.today, status: 'Idea', benefits: [] } : { date: Domain.today, status: 'Idea', benefits: [] });
    const fields = [{ name: 'title', label: 'Improvement title', required: true, full: true }, { name: 'zone', label: 'Zone', type: 'select', options: UI.zoneOpts(), required: true }, { name: 's', label: '5S category', type: 'select', options: FS.S_KEYS.map((s) => [s, s + ' ' + Domain.sName(s)]) }, { name: 'before', label: 'Before condition', type: 'textarea', required: true }, { name: 'idea', label: 'Improvement idea', type: 'textarea', required: true }, { name: 'desc', label: 'Improvement description', type: 'textarea', full: true }, { name: 'after', label: 'After condition', type: 'textarea', full: true }, { name: 'owner', label: 'Owner', type: 'select', options: UI.userOpts(), required: true }, { name: 'date', label: 'Date', type: 'date', required: true }, { name: 'saving', label: 'Cost saving (₹, if applicable)', type: 'number', min: 0 }, { name: 'status', label: 'Status', type: 'select', options: ['Idea', 'In Progress', 'Implemented', 'Verified', 'Closed'], required: true }, { name: 'benefits', label: 'Benefits', type: 'multi', options: ms.benefits || [], full: true }];
    let before = (i0 && i0.beforePhoto) || (fnd && (fnd.photos || [])[0]) || null; let after = (i0 && i0.afterPhoto) || null;
    const phHtml = () => `<div class="row" style="gap:16px"><div><div class="eyebrow">Before photo</div>${before ? UI.thumbs([before], { lg: true }) : '<div class="small faint">None</div>'}<button class="btn sm" data-act="imp-ph" data-k="before" style="margin-top:6px">${icon('camera')}Set before</button></div><div><div class="eyebrow">After photo</div>${after ? UI.thumbs([after], { lg: true }) : '<div class="small faint">None</div>'}<button class="btn sm" data-act="imp-ph" data-k="after" style="margin-top:6px">${icon('camera')}Set after</button></div></div>`;
    Acts['imp-ph'] = async (b) => { const r = await UI.capture({ kind: b.dataset.k, zone: init.zone }, { capture: false }); if (!r.length) return; if (b.dataset.k === 'before') before = r[0]; else after = r[0]; $('#imp-ph').innerHTML = phHtml(); };
    UI.modal({ title: i0 ? 'Edit improvement' : fnd ? 'Convert finding to Kaizen' : 'New improvement', size: 'wide', body: UI.form(fields, init) + `<div class="divider" style="margin:14px 0"></div><div id="imp-ph">${phHtml()}</div>`, actions: [{ label: 'Cancel' }, { label: 'Save', cls: 'primary', onClick: async (m) => {
      const v = UI.readForm(m, fields); if (!v) return false; if (['Implemented', 'Verified', 'Closed'].includes(v.status) && !after) { UI.toast('Add an after photo before marking the improvement implemented', 'bad'); return false; }
      const z = Domain.zone(v.zone); const doc = Object.assign({}, i0 || {}, v, { plant: z.plant, apu: z.apu, dept: z.dept, beforePhoto: before, afterPhoto: after, findingId: init.findingId || '' });
      let id = i0 && i0.id; if (!i0) { const n = await Store.nextNo('IMP'); id = n.id; doc.no = n.no; doc.createdAt = nowISO(); doc.createdBy = App.user.id; }
      await Store.put('improvements', id, doc); Domain.log('Improvements', doc.no, i0 ? 'Improvement updated' : 'Improvement created', i0 ? i0.status : '', v.status);
      if (!i0) setTimeout(() => App.go('improvement', { id }), 30); } }] });
  },
  async 'imp-verify'(el) { const i = Store.get('improvements', el.dataset.id); await Store.patch('improvements', i.id, { status: 'Verified', verifiedBy: App.user.id, verifiedAt: nowISO() }); Domain.log('Improvements', i.no, 'Benefit verified', i.status, 'Verified'); },
});
