/* ===== Master data, System settings, User Role, Audit Trail ===== */
const saveSettings = async (part, label) => { const prev = Domain.settings(); const keys = Object.keys(part); await Store.patch('cfg', 'settings', part); Domain.log('Master', 'Settings: ' + label, 'Configuration changed', keys.map((k) => `${k}=${JSON.stringify(prev[k] ?? '').slice(0, 120)}`).join('; '), keys.map((k) => `${k}=${JSON.stringify(part[k]).slice(0, 120)}`).join('; ')); UI.toast(label + ' saved', 'good'); };
const saveMasters = async (part, label, rec, action) => { const prev = Domain.masters(); await Store.patch('cfg', 'masters', part); Domain.log('Master', rec || label, action || 'Master data changed', Object.keys(part).map((k) => `${k}: ${(prev[k] || []).length} items`).join('; '), Object.keys(part).map((k) => `${k}: ${(part[k] || []).length} items`).join('; ')); UI.toast(label + ' saved', 'good'); };

Pages.master = {
  perm: 'Master',
  render(p) {
    if (p.tab) { App.ui.mTab = p.tab; delete p.tab; }
    const tab = App.ui.mTab || 'org'; const edit = Domain.can('Master', 'edit');
    const tabs = [['org', 'Organization'], ['zones', 'Zones'], ['checksheets', 'Checksheets'], ['scoring', 'Scoring & Ratings'], ['timelines', 'NC Closure & WO Trigger'], ['lists', 'Lists'], ['workflow', 'Approval Workflow'], ['notif', 'Notification Rules'], ['system', 'System Settings']];
    const fn = { org: this.org, zones: this.zones, checksheets: this.checksheets, scoring: this.scoring, timelines: this.timelines, lists: this.lists, workflow: this.workflow, notif: this.notif, system: this.system }[tab];
    return `${UI.head('Master', [], '', edit ? 'Configuration masters. Every change is written to the audit trail.' : 'View only – changes require the System Administrator.')}${UI.tabs('mTab', tabs, tab)}${fn.call(this, edit)}`;
  },
  org(edit) {
    const ms = Domain.masters(); const btn = (kind, label) => (edit ? `<button class="btn sm" data-act="m-org" data-kind="${kind}">${icon('plus')}${label}</button>` : '');
    const ed = (kind, id) => (edit ? `<button class="btn sm ghost" data-act="m-org" data-kind="${kind}" data-id="${esc(id)}">${icon('edit')}</button>` : '');
    const stb = (s) => UI.badge(s || 'Active', (s || 'Active') === 'Active' ? 'b-green' : 'b-gray');
    const zc = (fn) => Store.all('zones').filter(fn).length;
    return `<div class="banner info">${icon('layers')}<span>Hierarchy: Plant → APU → Department → Section → Zone</span></div><div class="grid">
      <div class="c6">${UI.card('Plants', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Code</th><th>Plant</th><th>Location</th><th class="num">Zones</th><th>Status</th><th></th></tr></thead><tbody>${(ms.plants || []).map((p) => `<tr><td class="mono">${esc(p.code)}</td><td><b>${esc(p.name)}</b></td><td>${esc(p.location)}</td><td class="num">${zc((z) => z.plant === p.id)}</td><td>${stb(p.status)}</td><td class="right">${ed('plants', p.id)}</td></tr>`).join('')}</tbody></table></div>`, { right: btn('plants', 'Plant') })}</div>
      <div class="c6">${UI.card('APUs', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Code</th><th>APU</th><th>Plant</th><th>5S Facilitator</th><th class="num">Zones</th><th>Status</th><th></th></tr></thead><tbody>${(ms.apus || []).map((a) => `<tr><td class="mono">${esc(a.code)}</td><td><b>${esc(a.name)}</b></td><td>${esc(Domain.plantName(a.plant))}</td><td>${UI.person(a.facilitator)}</td><td class="num">${zc((z) => z.apu === a.id)}</td><td>${stb(a.status)}</td><td class="right">${ed('apus', a.id)}</td></tr>`).join('')}</tbody></table></div>`, { right: btn('apus', 'APU') })}</div>
      <div class="c6">${UI.card('Departments', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Department</th><th class="num">Zones</th><th class="num">Employees</th><th>Status</th><th></th></tr></thead><tbody>${(ms.departments || []).map((d) => `<tr><td><b>${esc(d.name)}</b></td><td class="num">${zc((z) => z.dept === d.name)}</td><td class="num">${Store.all('users').filter((u) => u.dept === d.name).length}</td><td>${stb(d.status)}</td><td class="right">${ed('departments', d.id)}</td></tr>`).join('')}</tbody></table></div>`, { right: btn('departments', 'Department') })}</div>
      <div class="c6">${UI.card('Sections / Areas', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Section</th><th>Department</th><th class="num">Zones</th><th>Status</th><th></th></tr></thead><tbody>${(ms.sections || []).map((s) => `<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.dept)}</td><td class="num">${zc((z) => z.section === s.name && z.dept === s.dept)}</td><td>${stb(s.status)}</td><td class="right">${ed('sections', s.id)}</td></tr>`).join('')}</tbody></table></div>`, { right: btn('sections', 'Section') })}</div></div>`;
  },
  zones(edit) {
    const f = App.st('mzF', { apu: '', type: '', status: '', q: '' });
    const list = Store.all('zones').filter((z) => (!f.apu || z.apu === f.apu) && (!f.type || z.type === f.type) && (!f.status || z.status === f.status) && (!f.q || (z.code + ' ' + z.name + ' ' + z.dept).toLowerCase().includes(f.q.toLowerCase())));
    return `<div class="filters"><input type="search" placeholder="Search zone" value="${esc(f.q)}" data-input="mz-q" aria-label="Search zones">${UI.sel('mzF:apu', [['', 'All APUs']].concat((Domain.masters().apus || []).map((a) => [a.id, a.name])), f.apu)}${UI.sel('mzF:type', [['', 'All zone types']].concat((Domain.masters().zoneTypes || []).map((t) => [t, t])), f.type)}${UI.sel('mzF:status', [['', 'Any status'], ['Active', 'Active'], ['Inactive', 'Inactive']], f.status)}<span class="grow"></span>${edit ? `<button class="btn primary" data-act="zone-edit">${icon('plus')}New zone</button>` : ''}</div>
      ${UI.card('', UI.table('mzones', [{ k: 'code', h: 'Zone ID', r: (z) => `<b class="mono">${esc(z.code)}</b>` }, { k: 'name', h: 'Zone name', r: (z) => `<b>${esc(z.name)}</b><div class="small muted">${esc(z.location || '')}</div>` }, { k: 'apu', h: 'Plant / APU', r: (z) => `${esc(Domain.plantName(z.plant))}<div class="small muted">${esc(Domain.apuName(z.apu))}</div>` }, { k: 'dept', h: 'Department', r: (z) => `${esc(z.dept)}<div class="small muted">${esc(z.section || '')}</div>` }, { k: 'type', h: 'Type' }, { k: 'risk', h: 'Risk', r: (z) => UI.badge(z.risk, z.risk === 'High' ? 'b-red' : z.risk === 'Medium' ? 'b-amber' : 'b-green') }, { k: 'leader', h: 'Leader / Backup', r: (z) => `${esc(Domain.uname(z.leader))}<div class="small muted">${esc(Domain.uname(z.backup))}</div>` }, { k: 'members', h: 'Members', num: true, r: (z) => (z.members || []).length }, { k: 'frequency', h: 'Frequency', r: (z) => `${esc(z.frequency)}<div class="small muted">${z.duration} min</div>` }, { k: 'area', h: 'Area m²', num: true }, { k: 'status', h: 'Status', r: (z) => UI.badge(z.status, z.status === 'Active' ? 'b-green' : 'b-gray') }, edit ? { k: 'x', h: '', sortable: false, r: (z) => `<button class="btn sm" data-act="zone-edit" data-id="${z.id}">${icon('edit')}Edit</button>` } : null].filter(Boolean), list, { pageSize: 30 }))}`;
  },
  checksheets(edit) {
    const fams = groupBy(Store.all('checksheets'), (c) => c.family);
    return `<div class="row between" style="margin-bottom:12px"><div class="small muted grow">Released versions are locked. Old audits always keep the version used at the time of audit; changes go into a new version.</div>${edit ? `<button class="btn primary" data-act="cs-new">${icon('plus')}New checksheet</button>` : ''}</div>
      <div class="stack">${Object.entries(fams).map(([fam, list]) => { list.sort((a, b) => Number(b.version) - Number(a.version)); const act = list.find((c) => c.status === 'Active'); const used = Store.all('workorders').filter((w) => list.some((c) => c.id === w.checksheetId)); return UI.card(esc((act || list[0]).name), `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Version</th><th>Status</th><th class="num">Questions</th><th>Zone types</th><th>Effective</th><th>Change note</th><th class="num">Audits</th><th></th></tr></thead><tbody>${list.map((c) => `<tr><td><b class="mono">v${esc(c.version)}</b></td><td>${UI.badge(c.status, c.status === 'Active' ? 'b-green' : c.status === 'Draft' ? 'b-amber' : 'b-gray')}</td><td class="num">${(c.questions || []).filter((q) => q.active !== false).length}</td><td class="small">${esc((c.zoneTypes || []).join(', '))}</td><td class="small nowrap">${fmtDate(c.effectiveFrom)} → ${c.effectiveTo ? fmtDate(c.effectiveTo) : 'open'}</td><td class="small">${esc(c.changeNote || '')}</td><td class="num">${used.filter((w) => w.checksheetId === c.id).length}</td><td class="right nowrap"><button class="btn sm" data-act="cs-open" data-id="${c.id}">${c.status === 'Draft' && edit ? icon('edit') + 'Edit' : icon('eye') + 'View'}</button>${edit && c.status === 'Active' && !list.some((x) => x.status === 'Draft') ? ` <button class="btn sm" data-act="cs-version" data-id="${c.id}">${icon('copy')}New version</button>` : ''}${edit && c.status === 'Draft' ? ` <button class="btn sm primary" data-act="cs-release" data-id="${c.id}">Release</button>` : ''}</td></tr>`).join('')}</tbody></table></div>`, { sub: `<span class="mono">${esc(fam)}</span>` }); }).join('')}</div>`;
  },
  scoring(edit) {
    const st = Domain.settings(); const dis = edit ? '' : 'disabled';
    return `<div class="grid"><div class="c6">${UI.card('Rating scale', `<div class="tbl-wrap"><table class="tbl" id="rs"><thead><tr><th>Score</th><th>Rating label</th></tr></thead><tbody>${(st.ratingScale || []).map((r, i) => `<tr><td class="num" style="width:80px"><input type="number" min="0" max="10" value="${r.value}" data-i="${i}" data-k="value" ${dis} style="width:64px;padding:4px 6px;border:1px solid var(--line);border-radius:5px"></td><td><input value="${esc(r.label)}" data-i="${i}" data-k="label" ${dis} style="width:100%;padding:4px 6px;border:1px solid var(--line);border-radius:5px"></td></tr>`).join('')}<tr><td class="num">N/A</td><td class="muted small">Not applicable – excluded from the denominator</td></tr></tbody></table></div>${edit ? '<button class="btn sm primary" data-act="m-rs" style="margin-top:10px">Save rating scale</button>' : ''}`)}
        <div style="height:16px"></div>${UI.card('Score bands', `<div class="tbl-wrap"><table class="tbl" id="bands"><thead><tr><th>From %</th><th>Label</th><th>Colour</th><th>Preview</th></tr></thead><tbody>${(st.bands || []).map((b, i) => `<tr><td><input type="number" min="0" max="100" value="${b.min}" data-i="${i}" data-k="min" ${dis} style="width:70px;padding:4px 6px;border:1px solid var(--line);border-radius:5px"></td><td><input value="${esc(b.label)}" data-i="${i}" data-k="label" ${dis} style="width:100%;padding:4px 6px;border:1px solid var(--line);border-radius:5px"></td><td><input type="color" value="${b.color}" data-i="${i}" data-k="color" ${dis}></td><td><span class="score" style="background:${b.color}">${b.min}%</span></td></tr>`).join('')}</tbody></table></div>${edit ? '<button class="btn sm primary" data-act="m-bands" style="margin-top:10px">Save bands</button>' : ''}`, { sub: 'Used by the heat map, score badges and scorecards' })}</div>
      <div class="c6">${UI.card('Scoring method & thresholds', UI.form(this.scoringFields(edit), Object.assign({}, st, Object.fromEntries(FS.S_KEYS.map((s) => ['w' + s, (st.sWeights || {})[s] ?? 1])))) + (edit ? '<button class="btn primary" data-act="m-scoring" style="margin-top:12px">Save scoring settings</button>' : ''), { sub: 'S score = Σ score × weight ÷ Σ max × weight × 100' })}
        <div style="height:16px"></div>${UI.card('5S terminology', UI.form(FS.S_KEYS.flatMap((s) => [{ name: s + 'n', label: s + ' name', disabled: !edit }, { name: s + 'j', label: s + ' Japanese term', disabled: !edit }]), Object.fromEntries(FS.S_KEYS.flatMap((s) => [[s + 'n', ((st.sNames || {})[s] || {}).name], [s + 'j', ((st.sNames || {})[s] || {}).jp]]))) + (edit ? '<button class="btn primary" data-act="m-terms" style="margin-top:12px">Save terminology</button>' : ''))}</div></div>`;
  },
  scoringFields(edit) { return [{ name: 'scoringMethod', label: 'Overall score method', type: 'select', blank: false, options: [['average', 'Average of S1–S5'], ['weighted', 'Weighted by S weights']], disabled: !edit }, { name: 'findingThreshold', label: 'Finding mandatory at score ≤', type: 'number', min: 0, max: 5, disabled: !edit }, { name: 'targetScore', label: 'Target score %', type: 'number', min: 0, max: 100, disabled: !edit }, { name: 'alertScoreThreshold', label: 'Zone alert below %', type: 'number', min: 0, max: 100, disabled: !edit }, { name: 'scoreDropAlert', label: 'Alert on score drop of (pts)', type: 'number', min: 1, max: 100, disabled: !edit }, { name: 'completionTarget', label: 'Audit completion target %', type: 'number', min: 0, max: 100, disabled: !edit }].concat(FS.S_KEYS.map((s) => ({ name: 'w' + s, label: s + ' weight', type: 'number', min: 0, step: 0.1, disabled: !edit }))); },
  timelines(edit) {
    const st = Domain.settings(); const ms = Domain.masters(); const dis = edit ? '' : 'disabled'; const inp = (k, v) => `<input type="number" min="0" max="365" value="${v ?? ''}" data-k="${esc(k)}" ${dis} style="width:90px;padding:5px 8px;border:1px solid var(--line);border-radius:5px">`;
    return `<div class="grid"><div class="c6">${UI.card('NC Closure Timeline', `<div class="tbl-wrap"><table class="tbl" id="ncc"><thead><tr><th>Severity</th><th>Close within (days)</th><th>Example due date for an audit today</th></tr></thead><tbody>${(ms.severities || []).map((s) => `<tr><td>${UI.sev(s.name)}</td><td>${inp(s.name, (st.ncClosure || {})[s.name])}</td><td class="small">${fmtDate(FS.addDays(Domain.today, (st.ncClosure || {})[s.name] || 0))}</td></tr>`).join('')}</tbody></table></div>${edit ? '<button class="btn primary" data-act="m-ncc" style="margin-top:10px">Save NC closure timeline</button>' : ''}`, { sub: 'Sets the default finding due date and action target date by severity' })}</div>
      <div class="c6">${UI.card('Work Order Trigger Duration', `<div class="tbl-wrap"><table class="tbl" id="wot"><thead><tr><th>Frequency</th><th>Generate WO (days before)</th><th>Due after planned (days)</th></tr></thead><tbody>${(ms.frequencies || []).map((f) => `<tr><td><b>${esc(f)}</b></td><td>${inp('t:' + f, (st.woTrigger || {})[f])}</td><td>${inp('g:' + f, (st.woGrace || {})[f])}</td></tr>`).join('')}</tbody></table></div>${UI.form([{ name: 'auditDueSoonDays', label: 'Audit "due soon" alert (days)', type: 'number', min: 0, disabled: !edit }, { name: 'actionDueSoonDays', label: 'Action "due soon" alert (days)', type: 'number', min: 0, disabled: !edit }], st)}${edit ? '<button class="btn primary" data-act="m-wot" style="margin-top:12px">Save trigger settings</button>' : ''}`, { sub: 'A work order is created automatically this many days before each planned audit' })}</div></div>`;
  },
  lists(edit) {
    const ms = Domain.masters();
    const L = [['zoneTypes', 'Zone types'], ['findingCategories', 'Finding categories'], ['priorities', 'Priorities'], ['auditTypes', 'Audit types'], ['frequencies', 'Audit frequencies'], ['actionTypes', 'Action types'], ['benefits', 'Improvement benefits'], ['riskClasses', 'Risk classifications']];
    return `<div class="grid">${L.map(([k, t]) => `<div class="c6">${UI.card(t, `<div class="row tight">${(ms[k] || []).map((v, i) => `<span class="chip">${esc(v)}${edit ? `<button data-act="m-list-del" data-k="${k}" data-i="${i}" aria-label="Remove ${esc(v)}">×</button>` : ''}</span>`).join('')}</div>${edit ? `<div class="row" style="margin-top:10px"><input placeholder="Add ${esc(t.toLowerCase().replace(/s$/, ''))}" id="ml-${k}" style="flex:1;min-width:0;height:34px;border:1px solid var(--line);border-radius:7px;padding:0 10px"><button class="btn sm" data-act="m-list-add" data-k="${k}">${icon('plus')}Add</button></div>` : ''}`)}</div>`).join('')}
      <div class="c6">${UI.card('Severities', `<div class="tbl-wrap"><table class="tbl" id="sevs"><thead><tr><th>Severity</th><th>Colour</th></tr></thead><tbody>${(ms.severities || []).map((s, i) => `<tr><td>${UI.sev(s.name)}</td><td><input type="color" value="${s.color}" data-i="${i}" ${edit ? '' : 'disabled'}></td></tr>`).join('')}</tbody></table></div>${edit ? '<button class="btn sm primary" data-act="m-sev" style="margin-top:10px">Save colours</button>' : ''}`)}</div></div>`;
  },
  workflow(edit) {
    const st = Domain.settings(); const ms = Domain.masters(); const levels = ['Zone Leader', '5S Facilitator', 'Management'];
    return UI.card('Approval workflow by audit type', `<div class="small muted" style="margin-bottom:10px">Auditor → Zone Leader → 5S Facilitator → Management. Tick the levels each audit type needs; an audit type with no levels is approved on submission.</div><div class="tbl-wrap"><table class="tbl" id="wf"><thead><tr><th>Audit type</th>${levels.map((l) => `<th class="center">${l}</th>`).join('')}<th>Flow</th></tr></thead><tbody>${(ms.auditTypes || []).map((t) => { const cur = (st.approvals || {})[t] || []; return `<tr><td><b>${esc(t)}</b></td>${levels.map((l) => `<td class="center"><input type="checkbox" data-t="${esc(t)}" data-l="${l}" ${cur.includes(l) ? 'checked' : ''} ${edit ? '' : 'disabled'}></td>`).join('')}<td class="small">Auditor${cur.map((x) => ' → ' + esc(x)).join('')}</td></tr>`; }).join('')}</tbody></table></div>${edit ? '<button class="btn primary" data-act="m-wf" style="margin-top:12px">Save workflow</button>' : ''}`);
  },
  notif(edit) {
    const st = Domain.settings(); const dis = edit ? '' : 'disabled';
    return UI.card('Notification rules', `<div class="tbl-wrap"><table class="tbl" id="nr"><thead><tr><th>Event</th><th class="center">In-app</th><th class="center">Email</th><th class="center">Messaging</th><th>Recipients</th></tr></thead><tbody>${(st.notificationRules || []).map((r, i) => `<tr><td><b>${esc(r.event)}</b></td>${['inapp', 'email', 'msg'].map((c) => `<td class="center"><input type="checkbox" data-i="${i}" data-c="${c}" ${r[c] ? 'checked' : ''} ${dis}></td>`).join('')}<td><input value="${esc(r.to)}" data-i="${i}" data-c="to" ${dis} style="width:100%;padding:4px 8px;border:1px solid var(--line);border-radius:5px"></td></tr>`).join('')}</tbody></table></div><div class="small faint" style="margin-top:8px">In this demo, in-app notifications are delivered live; email and messaging are recorded on each notification as the channels that the server edition sends through SMTP / messaging integration.</div>${edit ? '<button class="btn primary" data-act="m-nr" style="margin-top:12px">Save notification rules</button>' : ''}`);
  },
  system(edit) {
    const st = Domain.settings(); const fields = [{ name: 'appTitle', label: 'Application title' }, { name: 'fiscalYearStart', label: 'Fiscal year starts in month', type: 'select', blank: false, options: MON.map((m, i) => [String(i + 1), m]) }, { name: 'timezone', label: 'Time zone', type: 'select', blank: false, options: ['Asia/Kolkata', 'Asia/Singapore', 'Asia/Dubai', 'Europe/London', 'Europe/Berlin', 'America/New_York', 'America/Chicago', 'UTC'] }, { name: 'dateFormat', label: 'Date format', type: 'select', blank: false, options: ['DD-MMM-YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD', 'MM/DD/YYYY'] }, { name: 'language', label: 'Language', type: 'select', blank: false, options: ['English', 'Hindi', 'Tamil', 'German', 'Japanese'] }, { name: 'reportHeader', label: 'Report header line', ph: '5S MANAGEMENT SYSTEM' }, { name: 'docVersion', label: 'Report document version', ph: 'Rev 1.0' }, { name: 'nAUD', label: 'Audit work order number format', help: 'Tokens: {T} type, {YYYY} year, {YY}, {N6} running number' }, { name: 'nFND', label: 'Finding number format' }, { name: 'nACT', label: 'Action number format' }, { name: 'nIMP', label: 'Improvement number format' }].map((f) => Object.assign(f, { disabled: !edit }));
    const v = Object.assign({}, st, { fiscalYearStart: String(st.fiscalYearStart || 4), nAUD: (st.numbering || {}).AUD, nFND: (st.numbering || {}).FND, nACT: (st.numbering || {}).ACT, nIMP: (st.numbering || {}).IMP });
    const c = Store.get('cfg', 'counters') || {};
    return `<div class="grid"><div class="c8">${UI.card('System settings', UI.form(fields, v) + (edit ? '<button class="btn primary" data-act="m-sys" style="margin-top:12px">Save system settings</button>' : ''))}</div><div class="c4">${UI.card('Number preview', ['AUD', 'FND', 'ACT', 'IMP'].map((k) => `<div class="row between" style="padding:5px 0;border-bottom:1px solid var(--line-2)"><span class="small muted">${{ AUD: 'Next audit', FND: 'Next finding', ACT: 'Next action', IMP: 'Next improvement' }[k]}</span><b class="mono">${esc(FS.formatNo((st.numbering || {})[k], k, new Date().getFullYear(), (c[k] || 0) + 1))}</b></div>`).join(''))}<div style="height:16px"></div>${UI.card('Data & backup', `<div class="small muted">The demo keeps shared data in the artifact database. The server edition runs nightly PostgreSQL backups (see the deployment guide).</div><div class="kv" style="margin-top:10px"><div><div class="k">Users</div><div class="v">${Store.all('users').length}</div></div><div><div class="k">Zones</div><div class="v">${Store.all('zones').length}</div></div><div><div class="k">Work orders</div><div class="v">${Store.all('workorders').length}</div></div><div><div class="k">Findings</div><div class="v">${Store.all('findings').length}</div></div><div><div class="k">Actions</div><div class="v">${Store.all('actions').length}</div></div></div>${edit ? `<button class="btn sm" style="margin-top:12px" data-act="m-export">${icon('download')}Export configuration (JSON)</button>` : ''}`)}</div></div>`;
  },
};

/* checksheet editor */
const CsEd = {
  open(id) {
    const c = Store.get('checksheets', id); const ro = c.status !== 'Draft' || !Domain.can('Master', 'edit'); CsEd.cur = clone(c); CsEd.ro = ro;
    UI.modal({ title: `${esc(c.name)} <span class="mono faint" style="font-size:.7em">v${esc(c.version)}</span>`, sub: ro ? `${c.status} – read only. Create a new version to change the criteria.` : 'Draft – edit questions, then release from the checksheet list.', size: 'xl', body: CsEd.body(), actions: ro ? [{ label: 'Close' }] : [{ label: 'Cancel' }, { label: 'Save draft', cls: 'primary', onClick: async (m) => { CsEd.read(m); if (!CsEd.cur.name) { UI.toast('Name is required', 'bad'); return false; } await Store.put('checksheets', c.id, CsEd.cur); Domain.log('Master', c.id, 'Checksheet draft saved', '', `${CsEd.cur.questions.length} questions`); UI.toast('Draft saved', 'good'); } }] });
  },
  body() {
    const c = CsEd.cur; const ro = CsEd.ro; const dis = ro ? 'disabled' : ''; const ms = Domain.masters();
    const inp = (q, i, k, w, t = 'text') => `<input ${t === 'number' ? 'type="number" step="0.5"' : ''} value="${esc(q[k] ?? '')}" data-q="${i}" data-k="${k}" ${dis} style="width:${w};padding:4px 6px;border:1px solid var(--line);border-radius:5px;background:var(--surface)">`;
    const chk = (q, i, k) => `<input type="checkbox" data-q="${i}" data-k="${k}" ${q[k] ? 'checked' : ''} ${dis}>`;
    return `<div class="form three" id="cs-h">${UI.field({ name: 'name', label: 'Checksheet name', required: true, disabled: ro }, c.name)}${UI.field({ name: 'effectiveFrom', label: 'Effective from', type: 'date', disabled: ro }, c.effectiveFrom)}${UI.field({ name: 'changeNote', label: 'Change note', disabled: ro }, c.changeNote)}${UI.field({ name: 'zoneTypes', label: 'Applies to zone types', type: 'multi', options: ms.zoneTypes || [], full: true }, c.zoneTypes)}</div>
      <div class="divider" style="margin:14px 0"></div><div class="tbl-wrap" style="max-height:56vh"><table class="tbl" id="cs-q"><thead><tr><th>ID</th><th>S</th><th>Subcategory</th><th style="min-width:280px">Question</th><th style="min-width:200px">Audit guidance</th><th>Response</th><th>Min</th><th>Max</th><th>Weight</th><th title="Mandatory">Mand.</th><th title="Evidence required">Evid.</th><th title="Photograph required">Photo</th><th title="Finding required when low">Find.</th><th>Active</th>${ro ? '' : '<th></th>'}</tr></thead><tbody>${c.questions.map((q, i) => `<tr><td class="mono small">${esc(q.qid)}</td><td><select data-q="${i}" data-k="s" ${dis}>${FS.S_KEYS.map((s) => `<option ${q.s === s ? 'selected' : ''}>${s}</option>`).join('')}</select></td><td>${inp(q, i, 'sub', '130px')}</td><td><textarea data-q="${i}" data-k="text" ${dis} rows="2" style="width:100%;min-width:260px;padding:4px 6px;border:1px solid var(--line);border-radius:5px;background:var(--surface)">${esc(q.text)}</textarea></td><td><textarea data-q="${i}" data-k="guidance" ${dis} rows="2" style="width:100%;min-width:180px;padding:4px 6px;border:1px solid var(--line);border-radius:5px;background:var(--surface)">${esc(q.guidance || '')}</textarea></td><td><select data-q="${i}" data-k="rtype" ${dis}>${[['score', 'Score'], ['yesno', 'Yes/No'], ['compliance', 'Compliant/NC'], ['passfail', 'Pass/Fail']].map(([v, l]) => `<option value="${v}" ${(q.rtype || 'score') === v ? 'selected' : ''}>${l}</option>`).join('')}</select></td><td>${inp(q, i, 'min', '52px', 'number')}</td><td>${inp(q, i, 'max', '52px', 'number')}</td><td>${inp(q, i, 'weight', '58px', 'number')}</td><td class="center">${chk(q, i, 'mandatory')}</td><td class="center">${chk(q, i, 'evidence')}</td><td class="center">${chk(q, i, 'photo')}</td><td class="center">${chk(q, i, 'findingReq')}</td><td class="center">${chk(q, i, 'active')}</td>${ro ? '' : `<td><button class="btn sm ghost" data-act="cs-qdel" data-i="${i}" aria-label="Delete question">${icon('trash')}</button></td>`}</tr>`).join('')}</tbody></table></div>${ro ? '' : `<div class="row" style="margin-top:10px">${FS.S_KEYS.map((s) => `<button class="btn sm" data-act="cs-qadd" data-s="${s}">${icon('plus')}${s} question</button>`).join('')}</div>`}`;
  },
  read(m) {
    const h = $('#cs-h', m); ['name', 'effectiveFrom', 'changeNote'].forEach((k) => { const i = $(`[name=${k}]`, h); if (i) CsEd.cur[k] = i.value; }); CsEd.cur.zoneTypes = $$('[data-multi="zoneTypes"] input:checked', h).map((i) => i.value);
    $$('#cs-q [data-q]', m).forEach((el) => { const q = CsEd.cur.questions[Number(el.dataset.q)]; const k = el.dataset.k; q[k] = el.type === 'checkbox' ? el.checked : ['min', 'max', 'weight'].includes(k) ? Number(el.value) : el.value; });
    if (!CsEd.ro) { const seen = {}; CsEd.cur.questions.forEach((q) => { seen[q.s] = (seen[q.s] || 0) + 1; if (!q.qid || !q.qid.startsWith(q.s)) q.qid = q.s + '-' + FS.pad(seen[q.s]); }); }
  },
  rerender() { const m = $('.modal'); CsEd.read(m); $('.modal-b', m).innerHTML = CsEd.body(); },
};
Object.assign(Acts, {
  'cs-open'(el) { CsEd.open(el.dataset.id); },
  'cs-qadd'(el) { const m = $('.modal'); CsEd.read(m); const s = el.dataset.s; const n = CsEd.cur.questions.filter((q) => q.s === s).length + 1; const idx = CsEd.cur.questions.map((q) => q.s).lastIndexOf(s); CsEd.cur.questions.splice(idx + 1, 0, { qid: s + '-' + FS.pad(n), s, sub: '', text: '', desc: '', guidance: '', max: 5, min: 1, weight: 1, mandatory: true, evidence: false, photo: false, findingReq: true, active: true, rtype: 'score' }); $('.modal-b', m).innerHTML = CsEd.body(); },
  'cs-qdel'(el) { const m = $('.modal'); CsEd.read(m); CsEd.cur.questions.splice(Number(el.dataset.i), 1); $('.modal-b', m).innerHTML = CsEd.body(); },
  async 'cs-version'(el) { const c = Store.get('checksheets', el.dataset.id); const nv = (Math.floor(Number(c.version)) + 1).toFixed(1); const id = c.family + '-V' + Math.floor(Number(nv)); if (Store.get('checksheets', id)) { UI.toast('Version ' + nv + ' already exists', 'bad'); return; } const d = clone(c); delete d.id; Object.assign(d, { version: nv, status: 'Draft', effectiveFrom: Domain.today, effectiveTo: '', createdBy: App.user.id, createdAt: nowISO(), changeNote: '' }); await Store.put('checksheets', id, d); Domain.log('Master', id, 'Checksheet version created', 'v' + c.version, 'v' + nv + ' (draft)'); setTimeout(() => CsEd.open(id), 60); },
  async 'cs-release'(el) {
    const c = Store.get('checksheets', el.dataset.id); if (!(c.questions || []).filter((q) => q.active !== false).length) { UI.toast('Add at least one active question', 'bad'); return; }
    if (!(await UI.confirm('Release version ' + c.version + '?', 'New work orders will use this version. Audits already created keep their version, and this version becomes read-only.', 'Release'))) return;
    const prev = Store.all('checksheets').filter((x) => x.family === c.family && x.status === 'Active');
    for (const p of prev) await Store.patch('checksheets', p.id, { status: 'Superseded', effectiveTo: FS.addDays(c.effectiveFrom || Domain.today, -1) });
    await Store.patch('checksheets', c.id, { status: 'Active', releasedAt: nowISO(), releasedBy: App.user.id }); Domain.log('Master', c.id, 'Checksheet version released', prev.map((p) => 'v' + p.version).join(','), 'v' + c.version); UI.toast('Version released', 'good');
  },
  'cs-new'() {
    const fields = [{ name: 'name', label: 'Checksheet name', required: true, full: true }, { name: 'family', label: 'Code', required: true, ph: 'CS-LAB', validate: (v) => (!/^[A-Z0-9-]+$/.test(v) ? 'Use capitals, digits and hyphens' : Store.all('checksheets').some((c) => c.family === v) ? 'Code already exists' : '') }, { name: 'copy', label: 'Start from', type: 'select', options: [['', 'Blank (one question per S)']].concat(Store.all('checksheets').filter((c) => c.status === 'Active').map((c) => [c.id, c.name])) }];
    UI.modal({ title: 'New checksheet', body: UI.form(fields), actions: [{ label: 'Cancel' }, { label: 'Create draft', cls: 'primary', onClick: async (m) => { const v = UI.readForm(m, fields); if (!v) return false; const src = v.copy ? Store.get('checksheets', v.copy) : null; const qs = src ? clone(src.questions) : FS.S_KEYS.map((s) => ({ qid: s + '-01', s, sub: '', text: '', desc: '', guidance: '', max: 5, min: 1, weight: 1, mandatory: true, evidence: false, photo: false, findingReq: true, active: true, rtype: 'score' })); const id = v.family + '-V1'; await Store.put('checksheets', id, { family: v.family, name: v.name, version: '1.0', status: 'Draft', zoneTypes: src ? src.zoneTypes : [], effectiveFrom: Domain.today, effectiveTo: '', createdBy: App.user.id, createdAt: nowISO(), questions: qs, changeNote: 'Initial release' }); Domain.log('Master', id, 'Checksheet created', '', v.name); setTimeout(() => CsEd.open(id), 60); } }] });
  },
  'mz-q'(el) { App.st('mzF', {}).q = el.value; clearTimeout(Acts._mz); Acts._mz = setTimeout(() => { App.render(); const i = $('[data-input="mz-q"]'); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } }, 300); },
  'zone-edit'(el) {
    const id = el.dataset.id; const z0 = id ? Store.get('zones', id) : null; const ms = Domain.masters();
    const fams = uniq(Store.all('checksheets').map((c) => c.family)).map((f) => { const c = Domain.activeChecksheet(f) || Store.all('checksheets').find((x) => x.family === f); return [f, c.name]; });
    const people = UI.userOpts();
    const fields = [{ name: 'code', label: 'Zone ID', required: true, disabled: !!z0, validate: (v) => (!z0 && Store.get('zones', v) ? 'Zone ID already exists' : !/^[A-Z0-9-]+$/.test(v) ? 'Use capitals, digits and hyphens' : '') }, { name: 'name', label: 'Zone name', required: true }, { name: 'plant', label: 'Plant', type: 'select', options: (ms.plants || []).map((p) => [p.id, p.name]), required: true }, { name: 'apu', label: 'APU', type: 'select', options: (ms.apus || []).map((a) => [a.id, a.name]), required: true }, { name: 'dept', label: 'Department', type: 'select', options: (ms.departments || []).map((d) => d.name), required: true }, { name: 'section', label: 'Section / Area', type: 'select', options: (ms.sections || []).map((s) => s.name) }, { name: 'location', label: 'Location' }, { name: 'area', label: 'Area / size (m²)', type: 'number', min: 0 }, { name: 'type', label: 'Zone type', type: 'select', options: ms.zoneTypes || [], required: true }, { name: 'risk', label: 'Risk classification', type: 'select', options: ms.riskClasses || ['High', 'Medium', 'Low'], required: true }, { name: 'frequency', label: 'Audit frequency', type: 'select', options: ms.frequencies || [], required: true }, { name: 'duration', label: 'Standard audit duration (min)', type: 'number', min: 5 }, { name: 'checksheet', label: 'Checksheet', type: 'select', options: fams, required: true }, { name: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'], required: true }, { name: 'effFrom', label: 'Effective from', type: 'date', required: true }, { name: 'effTo', label: 'Effective to', type: 'date', validate: (v, o) => (v && v < o.effFrom ? 'Must be after effective from' : '') }, { name: 'leader', label: 'Zone Leader', type: 'select', options: people, required: true }, { name: 'backup', label: 'Backup Leader', type: 'select', options: people, validate: (v, o) => (v && v === o.leader ? 'Backup must differ from the leader' : '') }, { name: 'members', label: 'Zone Members', type: 'multi', options: people, full: true }, { name: 'desc', label: 'Zone description', type: 'textarea', full: true }];
    let media = clone((z0 && z0.media) || []);
    const mh = () => `<div class="eyebrow" style="margin-bottom:6px">Zone photograph, layout, map, 5S standard photos, visual standards</div>${UI.thumbs(media, { remove: 'zm-del' }) || '<div class="small faint">None uploaded</div>'}<div class="row" style="margin-top:8px"><select id="zm-kind" style="height:34px;border:1px solid var(--line);border-radius:7px;padding:0 8px"><option>Zone photograph</option><option>Zone layout</option><option>Zone map</option><option>5S standard photo</option><option>Visual standard</option></select><button class="btn sm" data-act="zm-add">${icon('upload')}Upload</button></div>`;
    Acts['zm-add'] = async () => { const kind = $('#zm-kind').value; const r = await UI.capture({ kind, zone: id || '' }, { capture: false }); media = media.concat(r.map((x) => Object.assign(x, { kind, caption: kind }))); $('#zm').innerHTML = mh(); };
    Acts['zm-del'] = (b, e) => { e.stopPropagation(); media.splice(Number(b.dataset.i), 1); $('#zm').innerHTML = mh(); };
    UI.modal({ title: z0 ? 'Edit zone ' + esc(z0.code) : 'New zone', size: 'wide', body: UI.form(fields, z0 || { status: 'Active', effFrom: Domain.today, frequency: 'Monthly', duration: 45, risk: 'Medium', plant: App.plant !== 'all' ? App.plant : '' }, 'three') + `<div class="divider" style="margin:14px 0"></div><div id="zm">${mh()}</div>`, actions: [{ label: 'Cancel' }, { label: z0 ? 'Save zone' : 'Create zone', cls: 'primary', onClick: async (m) => {
      const v = UI.readForm(m, fields); if (!v) return false; if (z0) v.code = z0.code; const a = Domain.apu(v.apu); if (a && a.plant !== v.plant) { UI.toast(`${a.name} APU belongs to ${Domain.plantName(a.plant)}`, 'bad'); return false; }
      v.members = (v.members || []).filter((x) => x !== v.leader);
      const doc = Object.assign({}, z0 || {}, v, { media }); await Store.put('zones', v.code, doc);
      const ch = z0 ? Object.keys(v).filter((k) => JSON.stringify(v[k] ?? '') !== JSON.stringify(z0[k] ?? '')) : [];
      Domain.log('Master', 'Zone ' + v.code, z0 ? 'Zone modified' : 'Zone created', z0 ? ch.map((k) => `${k}: ${JSON.stringify(z0[k] ?? '')}`).join('; ') : '', z0 ? ch.map((k) => `${k}: ${JSON.stringify(v[k] ?? '')}`).join('; ') : v.name);
      if (z0 && z0.leader !== v.leader) Domain.log('Master', 'Zone ' + v.code, 'Zone Leader assigned', Domain.uname(z0.leader), Domain.uname(v.leader));
      if (!z0 && !Store.all('schedules').some((s) => s.zone === v.code)) UI.toast('Zone created. Add an audit schedule in the Audit Planner.', 'good'); } }] });
  },
  'm-org'(el) {
    const kind = el.dataset.kind; const ms = Domain.masters(); const list = clone(ms[kind] || []); const cur = el.dataset.id ? list.find((x) => x.id === el.dataset.id) : null;
    const F = { plants: [{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'Plant name', required: true }, { name: 'location', label: 'Location' }], apus: [{ name: 'code', label: 'Code', required: true }, { name: 'name', label: 'APU name', required: true }, { name: 'plant', label: 'Plant', type: 'select', options: (ms.plants || []).map((p) => [p.id, p.name]), required: true }, { name: 'facilitator', label: '5S Facilitator', type: 'select', options: UI.userOpts((u) => ['facilitator', 'admin'].includes(u.role)) }], departments: [{ name: 'name', label: 'Department name', required: true }], sections: [{ name: 'name', label: 'Section / area name', required: true }, { name: 'dept', label: 'Department', type: 'select', options: (ms.departments || []).map((d) => d.name), required: true }] }[kind].concat([{ name: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'], required: true }]);
    const label = { plants: 'Plant', apus: 'APU', departments: 'Department', sections: 'Section' }[kind];
    UI.modal({ title: (cur ? 'Edit ' : 'New ') + label, body: UI.form(F, cur || { status: 'Active' }), actions: [{ label: 'Cancel' }, { label: 'Save', cls: 'primary', onClick: async (m) => {
      const v = UI.readForm(m, F); if (!v) return false;
      if (cur) Object.assign(cur, v); else { const id = kind === 'plants' || kind === 'apus' ? v.code.toUpperCase() : (kind === 'departments' ? 'D' : 'SEC') + (list.length + 1 + Math.floor(Math.random() * 1000)); if (list.some((x) => x.id === id)) { UI.toast('Code already used', 'bad'); return false; } list.push(Object.assign({ id }, v)); }
      if (cur && v.status === 'Inactive' && kind === 'plants' && Store.all('zones').some((z) => z.plant === cur.id && z.status === 'Active')) UI.toast('Note: active zones still belong to this plant.');
      await saveMasters({ [kind]: list }, label, `${label} ${v.name}`, cur ? `${label} modified` : `${label} created`); } }] });
  },
  async 'm-rs'() { const rows = {}; $$('#rs [data-i]').forEach((i) => { const r = (rows[i.dataset.i] = rows[i.dataset.i] || {}); r[i.dataset.k] = i.dataset.k === 'value' ? Number(i.value) : i.value; }); await saveSettings({ ratingScale: Object.values(rows).sort((a, b) => b.value - a.value) }, 'Rating scale'); },
  async 'm-bands'() { const rows = {}; $$('#bands [data-i]').forEach((i) => { const r = (rows[i.dataset.i] = rows[i.dataset.i] || {}); r[i.dataset.k] = i.dataset.k === 'min' ? Number(i.value) : i.value; }); const b = Object.values(rows).sort((x, y) => y.min - x.min); if (b[b.length - 1].min !== 0) { UI.toast('The lowest band must start at 0%', 'bad'); return; } await saveSettings({ bands: b }, 'Score bands'); },
  async 'm-scoring'() { const f = Pages.master.scoringFields(true); const v = UI.readForm($('#content'), f); if (!v) return; const part = { scoringMethod: v.scoringMethod, findingThreshold: v.findingThreshold, targetScore: v.targetScore, alertScoreThreshold: v.alertScoreThreshold, scoreDropAlert: v.scoreDropAlert, completionTarget: v.completionTarget, sWeights: Object.fromEntries(FS.S_KEYS.map((s) => [s, v['w' + s] ?? 1])) }; await saveSettings(part, 'Scoring settings'); },
  async 'm-terms'() { const st = Domain.settings(); const n = clone(st.sNames || {}); FS.S_KEYS.forEach((s) => { n[s] = Object.assign({}, n[s] || {}, { name: $(`[name=${s}n]`).value || s, jp: $(`[name=${s}j]`).value }); }); await saveSettings({ sNames: n }, '5S terminology'); },
  async 'm-ncc'() { const o = {}; $$('#ncc [data-k]').forEach((i) => (o[i.dataset.k] = Number(i.value) || 0)); await saveSettings({ ncClosure: o }, 'NC Closure Timeline'); },
  async 'm-wot'() { const t = {}, g = {}; $$('#wot [data-k]').forEach((i) => { const [k, f] = i.dataset.k.split(':'); (k === 't' ? t : g)[f] = Number(i.value) || 0; }); await saveSettings({ woTrigger: t, woGrace: g, auditDueSoonDays: Number($('[name=auditDueSoonDays]').value) || 0, actionDueSoonDays: Number($('[name=actionDueSoonDays]').value) || 0 }, 'Work Order Trigger Duration'); },
  async 'm-list-add'(el) { const k = el.dataset.k; const i = $('#ml-' + k); const v = i.value.trim(); if (!v) return; const ms = Domain.masters(); if ((ms[k] || []).includes(v)) { UI.toast('Already in the list', 'bad'); return; } await saveMasters({ [k]: (ms[k] || []).concat(v) }, 'List', k, 'List value added: ' + v); },
  async 'm-list-del'(el) { const k = el.dataset.k; const ms = Domain.masters(); const l = (ms[k] || []).slice(); const [v] = l.splice(Number(el.dataset.i), 1); if (!(await UI.confirm('Remove value?', `Remove “${esc(v)}” from ${esc(k)}? Existing records keep their value.`, 'Remove', true))) return; await saveMasters({ [k]: l }, 'List', k, 'List value removed: ' + v); },
  async 'm-sev'() { const ms = Domain.masters(); const s = clone(ms.severities); $$('#sevs [data-i]').forEach((i) => (s[Number(i.dataset.i)].color = i.value)); await saveMasters({ severities: s }, 'Severity colours'); },
  async 'm-wf'() { const o = {}; (Domain.masters().auditTypes || []).forEach((t) => (o[t] = [])); $$('#wf input:checked').forEach((i) => o[i.dataset.t].push(i.dataset.l)); const order = ['Zone Leader', '5S Facilitator', 'Management']; Object.keys(o).forEach((k) => o[k].sort((a, b) => order.indexOf(a) - order.indexOf(b))); await saveSettings({ approvals: o }, 'Approval workflow'); },
  async 'm-nr'() { const r = clone(Domain.settings().notificationRules); $$('#nr [data-i]').forEach((i) => { const x = r[Number(i.dataset.i)]; x[i.dataset.c] = i.type === 'checkbox' ? i.checked : i.value; }); await saveSettings({ notificationRules: r }, 'Notification rules'); },
  async 'm-sys'() { const g = (n) => ($(`[name=${n}]`) || {}).value; const st = Domain.settings(); await saveSettings({ appTitle: g('appTitle'), fiscalYearStart: Number(g('fiscalYearStart')), timezone: g('timezone'), dateFormat: g('dateFormat'), language: g('language'), reportHeader: g('reportHeader'), docVersion: g('docVersion'), numbering: Object.assign({}, st.numbering, { AUD: g('nAUD'), FND: g('nFND'), ACT: g('nACT'), IMP: g('nIMP') }) }, 'System settings'); },
  async 'm-export'() { await Exporter.save('5s-configuration.json', JSON.stringify({ settings: Domain.settings(), masters: Domain.masters(), checksheets: Store.all('checksheets') }, null, 2)); },
});

/* ---------- User Role ---------- */
Pages.users = {
  perm: 'User Role',
  render(p) {
    if (p.q) { App.st('uF', {}).q = p.q; delete p.q; App.ui.uTab = 'users'; }
    const tab = App.ui.uTab || 'users';
    return `${UI.head('User Role', [], tab === 'users' && Domain.can('User Role', 'edit') ? `<button class="btn primary" data-act="u-edit">${icon('plus')}New user</button>` : '', 'Users, roles and permission-based access')}${UI.tabs('uTab', [['users', 'Users', Store.all('users').length], ['roles', 'Roles & Permissions']], tab)}${tab === 'users' ? this.users() : this.roles()}`;
  },
  users() {
    const f = App.st('uF', { role: '', status: '', plant: '', dept: '', q: '' }); const edit = Domain.can('User Role', 'edit');
    const list = Store.all('users').filter((u) => (!f.role || u.role === f.role) && (!f.status || u.status === f.status) && (!f.plant || (u.plants || [u.plant]).includes(f.plant)) && (!f.dept || u.dept === f.dept) && (!f.q || (u.id + ' ' + u.name + ' ' + u.email + ' ' + u.designation).toLowerCase().includes(f.q.toLowerCase())));
    return `<div class="filters"><input type="search" placeholder="Search name, ID, email" value="${esc(f.q)}" data-input="u-q" aria-label="Search users">${UI.sel('uF:role', [['', 'All roles']].concat(Object.entries(ROLE_LABEL)), f.role)}${UI.sel('uF:status', [['', 'Any status'], ['Active', 'Active'], ['Inactive', 'Inactive']], f.status)}${UI.sel('uF:plant', [['', 'All plants']].concat((Domain.masters().plants || []).map((p) => [p.id, p.name])), f.plant)}${UI.sel('uF:dept', [['', 'All departments']].concat((Domain.masters().departments || []).map((d) => [d.name, d.name])), f.dept)}</div>
      ${UI.card('', UI.table('users', [{ k: 'id', h: 'Employee ID', r: (u) => `<b class="mono">${esc(u.id)}</b>` }, { k: 'name', h: 'Employee', r: (u) => `<span class="person">${UI.av(u.id, 'sm')}<span><b>${esc(u.name)}</b><div class="small muted">${esc(u.designation || '')}</div></span></span>` }, { k: 'role', h: 'Role', r: (u) => UI.badge(ROLE_LABEL[u.role] || u.role, { admin: 'b-red', facilitator: 'b-indigo', auditor: 'b-blue', leader: 'b-teal', member: 'b-gray', management: 'b-amber' }[u.role]) }, { k: 'dept', h: 'Department / Section', r: (u) => `${esc(u.dept)}<div class="small muted">${esc(u.section || '')}</div>` }, { k: 'plant', h: 'Plant access', r: (u) => esc((u.plants || [u.plant]).map((p) => Domain.plantName(p)).join(', ')) }, { k: 'email', h: 'Contact', r: (u) => `<span class="small">${esc(u.email)}<br>${esc(u.mobile || '')}</span>` }, { k: 'manager', h: 'Reports to', r: (u) => esc(Domain.uname(u.manager)) }, { k: 'joinDate', h: 'Joined', r: (u) => fmtDate(u.joinDate) }, { k: 'status', h: 'Status', r: (u) => UI.badge(u.status, u.status === 'Active' ? 'b-green' : 'b-gray') }, edit ? { k: 'x', h: '', sortable: false, r: (u) => `<span class="row tight nowrap"><button class="btn sm" data-act="u-edit" data-id="${u.id}">${icon('edit')}</button><button class="btn sm" data-act="u-reset" data-id="${u.id}" title="Reset password">${icon('lock')}</button></span>` } : null].filter(Boolean), list, { pageSize: 25 }))}`;
  },
  roles() {
    const st = Domain.settings(); const P = st.permissions || {}; const edit = Domain.can('User Role', 'edit'); const funcs = Object.keys(P.admin || {}); const roles = Object.keys(ROLE_LABEL);
    const desc = { admin: 'Full access, users, masters and settings', facilitator: 'Plans audits, monitors completion and actions', auditor: 'Executes assigned audits and records findings', leader: 'Responds to findings and verifies actions in own zones', member: 'Updates assigned actions in own zone', management: 'Read-only dashboards, summaries and reports' };
    return `<div class="kpis six" style="margin-bottom:16px">${roles.map((r) => `<div class="kpi mini"><span class="k-l">${esc(ROLE_LABEL[r])}</span><span class="k-v">${Store.all('users').filter((u) => u.role === r && u.status === 'Active').length}</span><span class="k-s">${esc(desc[r])}</span></div>`).join('')}</div>
      ${UI.card('Permission matrix', `<div class="tbl-wrap"><table class="tbl matrix" id="perm"><thead><tr><th>Function</th>${roles.map((r) => `<th class="center">${esc(ROLE_LABEL[r])}</th>`).join('')}</tr></thead><tbody>${funcs.map((f) => `<tr><td><b>${esc(f)}</b></td>${roles.map((r) => `<td class="center"><select data-r="${r}" data-f="${esc(f)}" ${edit && r !== 'admin' ? '' : 'disabled'}>${['none', 'view', 'limited', 'edit'].map((l) => `<option value="${l}" ${(P[r] || {})[f] === l ? 'selected' : ''}>${{ none: 'No', view: 'View', limited: 'Limited', edit: '✓ Full' }[l]}</option>`).join('')}</select></td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="small faint" style="margin-top:8px">Data scope also applies: Zone Leaders and Members see only their own zones; Facilitators see their APUs; plant access limits every list.</div>${edit ? '<button class="btn primary" data-act="perm-save" style="margin-top:12px">Save permissions</button>' : ''}`)}`;
  },
};
Object.assign(Acts, {
  'u-q'(el) { App.st('uF', {}).q = el.value; clearTimeout(Acts._uq); Acts._uq = setTimeout(() => { App.render(); const i = $('[data-input="u-q"]'); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } }, 300); },
  'u-edit'(el) {
    const u0 = el.dataset.id ? Domain.user(el.dataset.id) : null; const ms = Domain.masters();
    const fields = [{ name: 'id', label: 'Employee ID', required: true, disabled: !!u0, validate: (v) => (!u0 && Store.get('users', v) ? 'Employee ID already exists' : !/^[A-Za-z0-9_-]{3,20}$/.test(v) ? '3–20 letters, digits, - or _' : '') }, { name: 'name', label: 'Employee name', required: true }, { name: 'designation', label: 'Designation' }, { name: 'dept', label: 'Department', type: 'select', options: (ms.departments || []).map((d) => d.name), required: true }, { name: 'section', label: 'Section', type: 'select', options: (ms.sections || []).map((s) => s.name) }, { name: 'email', label: 'Email', type: 'email', required: true, validate: (v) => (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(v) ? 'Enter a valid email' : '') }, { name: 'mobile', label: 'Mobile number', validate: (v) => (v && !/^[+\d][\d\s-]{7,16}$/.test(v) ? 'Enter a valid number' : '') }, { name: 'role', label: 'Role', type: 'select', options: Object.entries(ROLE_LABEL), required: true }, { name: 'manager', label: 'Reporting manager', type: 'select', options: UI.userOpts() }, { name: 'plant', label: 'Home plant', type: 'select', options: (ms.plants || []).map((p) => [p.id, p.name]), required: true }, { name: 'joinDate', label: 'Joining date', type: 'date' }, { name: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'], required: true }, { name: 'plants', label: 'Plant access', type: 'multi', options: (ms.plants || []).map((p) => [p.id, p.name]), required: true }, { name: 'apus', label: 'APU access', type: 'multi', options: (ms.apus || []).map((a) => [a.id, a.name]), required: true }].concat(u0 ? [] : [{ name: 'pwd1', label: 'Initial password', type: 'password', required: true, validate: (v) => (v.length < 8 ? 'At least 8 characters' : '') }]);
    UI.modal({ title: u0 ? 'Edit user ' + esc(u0.id) : 'New user', size: 'wide', body: UI.form(fields, u0 || { status: 'Active', role: 'member', plants: App.plant !== 'all' ? [App.plant] : [], plant: App.plant !== 'all' ? App.plant : '', joinDate: Domain.today }, 'three'), actions: [{ label: 'Cancel' }, { label: 'Save user', cls: 'primary', onClick: async (m) => {
      const v = UI.readForm(m, fields); if (!v) return false; if (u0) v.id = u0.id; if (!v.plants.includes(v.plant)) v.plants.push(v.plant);
      const doc = Object.assign({}, u0 || {}, v); delete doc.pwd1; if (!u0) doc.pwd = await pwdHash(v.id, v.pwd1);
      if (Store.adapter && Store.adapter.saveUser) await Store.adapter.saveUser(doc, v.pwd1); else await Store.put('users', v.id, doc);
      const ch = u0 ? Object.keys(v).filter((k) => JSON.stringify(v[k] ?? '') !== JSON.stringify(u0[k] ?? '')) : [];
      Domain.log('User Role', 'User ' + v.id, u0 ? 'User modified' : 'User created', u0 ? ch.map((k) => `${k}: ${JSON.stringify(u0[k] ?? '')}`).join('; ') : '', u0 ? ch.map((k) => `${k}: ${JSON.stringify(v[k] ?? '')}`).join('; ') : `${v.name}, ${ROLE_LABEL[v.role]}`);
      if (u0 && u0.role !== v.role) Domain.log('User Role', 'User ' + v.id, 'Role assigned', u0.role, v.role); UI.toast('User saved', 'good'); } }] });
  },
  'u-reset'(el) {
    const u = Domain.user(el.dataset.id); const tmp = 'Tmp@' + Math.random().toString(36).slice(2, 7) + Math.floor(Math.random() * 90 + 10);
    UI.modal({ title: 'Reset password', sub: `${esc(u.name)} (${esc(u.id)})`, body: `<p>Set a temporary password for this user? Share it with them directly; they can change it from their profile menu.</p><div class="panel" style="margin-top:10px"><div class="small muted">Temporary password</div><div class="row between"><b class="mono" style="font-size:18px" id="tmpw">${tmp}</b><button class="btn sm" data-act="copy-tmp">${icon('copy')}Copy</button></div></div>`, actions: [{ label: 'Cancel' }, { label: 'Reset password', cls: 'primary', onClick: async () => { if (Store.adapter && Store.adapter.resetPassword) await Store.adapter.resetPassword(u.id, tmp); else await Store.patch('users', u.id, { pwd: await pwdHash(u.id, tmp), pwdResetAt: nowISO() }); Domain.log('User Role', 'User ' + u.id, 'Password reset'); UI.toast('Password reset', 'good'); } }] });
  },
  'copy-tmp'() { const t = $('#tmpw').textContent; navigator.clipboard.writeText(t).then(() => UI.toast('Copied'), () => { const r = document.createRange(); r.selectNodeContents($('#tmpw')); const s = getSelection(); s.removeAllRanges(); s.addRange(r); UI.toast('Press Ctrl+C to copy'); }); },
  async 'perm-save'() { const P = clone(Domain.settings().permissions); $$('#perm select').forEach((s) => { if (!s.disabled) P[s.dataset.r][s.dataset.f] = s.value; }); await saveSettings({ permissions: P }, 'Role permissions'); },
});

/* ---------- Audit Trail ---------- */
Pages.trail = {
  perm: 'Audit Trail',
  rows() { return Store.all('logs').flatMap((d) => (d.entries || []).map((e) => Object.assign({ doc: d.id }, e))).sort((a, b) => (b.at || '').localeCompare(a.at || '')); },
  render() {
    const f = App.st('trF', { module: '', user: '', from: '', to: '', q: '' }); const all = this.rows();
    const list = all.filter((e) => (!f.module || e.module === f.module) && (!f.user || e.user === f.user) && (!f.from || e.at.slice(0, 10) >= f.from) && (!f.to || e.at.slice(0, 10) <= f.to) && (!f.q || (e.record + ' ' + e.action + ' ' + e.prev + ' ' + e.next).toLowerCase().includes(f.q.toLowerCase())));
    return `${UI.head('Audit Trail', [], `<button class="btn" data-act="trail-csv">${icon('download')}Export CSV</button>`, 'Every important transaction, with previous and new values. Entries are append-only and cannot be edited from the application.')}
      <div class="filters"><input type="search" placeholder="Search record or action" value="${esc(f.q)}" data-input="tr-q" aria-label="Search audit trail">${UI.sel('trF:module', [['', 'All modules']].concat(uniq(all.map((e) => e.module)).sort().map((m) => [m, m])), f.module)}${UI.sel('trF:user', [['', 'All users']].concat(uniq(all.map((e) => e.user)).map((u) => [u, Domain.uname(u)])), f.user)}<span class="lbl">From</span><input type="date" value="${esc(f.from)}" data-filter="trF:from" aria-label="From date"><span class="lbl">To</span><input type="date" value="${esc(f.to)}" data-filter="trF:to" aria-label="To date"></div>
      ${UI.card('', UI.table('trail', [{ k: 'at', h: 'Date / time', r: (e) => `<span class="nowrap">${fmtDT(e.at)}</span>` }, { k: 'user', h: 'User', r: (e) => UI.person(e.user, e.user), sortv: (e) => Domain.uname(e.user) }, { k: 'module', h: 'Module' }, { k: 'record', h: 'Record', r: (e) => `<span class="mono small">${esc(e.record)}</span>` }, { k: 'action', h: 'Action', r: (e) => `<b>${esc(e.action)}</b>` }, { k: 'prev', h: 'Previous value', r: (e) => `<div class="small muted clip" title="${esc(e.prev)}">${esc(e.prev)}</div>` }, { k: 'next', h: 'New value', r: (e) => `<div class="small clip" title="${esc(e.next)}">${esc(e.next)}</div>` }, { k: 'device', h: 'Device', r: (e) => `<span class="small faint">${esc(e.device || '')}</span>` }], list, { sort: 'at', dir: 'desc', pageSize: 40 }))}`;
  },
};
Object.assign(Acts, {
  'tr-q'(el) { App.st('trF', {}).q = el.value; clearTimeout(Acts._tq); Acts._tq = setTimeout(() => { App.render(); const i = $('[data-input="tr-q"]'); if (i) { i.focus(); i.setSelectionRange(i.value.length, i.value.length); } }, 300); },
  async 'trail-csv'() { const rows = Pages.trail.rows(); await Exporter.csv('5s-audit-trail.csv', ['Date/time', 'User', 'User name', 'Module', 'Record', 'Action', 'Previous value', 'New value', 'Device'], rows.map((e) => [e.at, e.user, Domain.uname(e.user), e.module, e.record, e.action, e.prev, e.next, e.device])); },
});
