/* ===== Reports & exports (PDF / Excel / CSV) ===== */
const LIBS = window.FIVES_MODE === 'api' ? { pdf: '/vendor/jspdf.umd.min.js', at: '/vendor/jspdf.plugin.autotable.min.js', xlsx: '/vendor/xlsx.full.min.js' } : { pdf: 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js', at: 'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js', xlsx: 'https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js' };
const pdfTxt = (s) => String(s ?? '').replace(/[–—\u2011]/g, '-').replace(/→/g, '->').replace(/₹/g, 'Rs.').replace(/≥/g, '>=').replace(/≤/g, '<=').replace(/…/g, '...').replace(/×/g, 'x').replace(/[‘’]/g, "'").replace(/[“”]/g, '"').replace(/[^\x00-\xFF]/g, '');
const Exporter = {
  _l: {},
  load(url) { return (this._l[url] = this._l[url] || new Promise((res, rej) => { const s = document.createElement('script'); s.src = url; s.onload = res; s.onerror = () => { delete this._l[url]; rej(new Error('The export library could not be loaded. Check the connection and try again.')); }; document.head.appendChild(s); })); },
  async save(filename, data) {
    if (App.downloads) { try { const r = await App.downloads.save({ filename, data }); if (r && r.status === 'saved') UI.toast('Saved ' + filename, 'good'); } catch (e) { if (e && e.code === 'declined') return; if (e && e.code === 'rate_limited') { UI.toast('A save prompt is already open.'); return; } UI.toast('The file could not be saved here (' + ((e && e.code) || 'error') + ').', 'bad'); } return; }
    if (App.blobDownload) { const b = data instanceof Blob ? data : new Blob([data]); const a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download = filename; document.body.appendChild(a); a.click(); setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 1000); return; }
    UI.toast('Downloads are not available in this view. Open the page in Claude to save files.', 'bad');
  },
  csv(filename, headers, rows) { const q = (v) => { const s = String(v ?? ''); return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s; }; return this.save(filename, '﻿' + [headers].concat(rows).map((r) => r.map(q).join(',')).join('\r\n')); },
  async xlsx(filename, sheets) {
    await this.load(LIBS.xlsx); const XLSX = window.XLSX; const wb = XLSX.utils.book_new(); const st = Domain.settings();
    sheets.forEach((s) => { const aoa = [[(st.reportHeader || '5S MANAGEMENT SYSTEM') + ' – ' + s.title]].concat(s.sub ? [[s.sub]] : [], [[`Generated ${fmtDT(nowISO())} by ${App.user.name}`], []], s.kv ? s.kv.concat([[]]) : [], [s.headers], s.rows); const ws = XLSX.utils.aoa_to_sheet(aoa); ws['!cols'] = s.headers.map((h, i) => ({ wch: Math.min(60, Math.max(String(h).length + 2, ...s.rows.slice(0, 200).map((r) => String(r[i] ?? '').length + 1))) })); XLSX.utils.book_append_sheet(wb, ws, String(s.name || s.title).replace(/[\\/?*[\]:]/g, ' ').slice(0, 31)); });
    const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' }); return this.save(filename, out);
  },
  async pdf(filename, { title, sub, orientation = 'landscape' }, build) {
    await this.load(LIBS.pdf); await this.load(LIBS.at);
    const { jsPDF } = window.jspdf; const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' }); const st = Domain.settings();
    const W = doc.internal.pageSize.getWidth(), H = doc.internal.pageSize.getHeight(); const M = 12; const TOP = 30;
    const ctx = { doc, W, H, M, y: TOP,
      ensure(h) { if (ctx.y + h > H - 16) { doc.addPage(); ctx.y = TOP; } },
      heading(t) { ctx.ensure(12); doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.setTextColor(23, 33, 43); doc.text(pdfTxt(t), M, ctx.y + 4); doc.setDrawColor(242, 183, 5); doc.setLineWidth(0.8); doc.line(M, ctx.y + 6, M + 18, ctx.y + 6); ctx.y += 10; },
      text(t, size = 9, bold) { doc.setFont('helvetica', bold ? 'bold' : 'normal'); doc.setFontSize(size); doc.setTextColor(40, 50, 60); const lines = doc.splitTextToSize(pdfTxt(t), W - 2 * M); ctx.ensure(lines.length * size * 0.45 + 2); doc.text(lines, M, ctx.y + 3); ctx.y += lines.length * size * 0.42 + 3; },
      kv(pairs, cols = 3) { const cw = (W - 2 * M) / cols; const rows = Math.ceil(pairs.length / cols); ctx.ensure(rows * 10 + 2); pairs.forEach(([k, v], i) => { const x = M + (i % cols) * cw, y = ctx.y + Math.floor(i / cols) * 10; doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(120, 130, 140); doc.text(pdfTxt(k), x, y + 3); doc.setFontSize(9.5); doc.setTextColor(23, 33, 43); doc.setFont('helvetica', 'bold'); doc.text(doc.splitTextToSize(pdfTxt(v ?? '-'), cw - 4)[0] || '-', x, y + 7.5); }); ctx.y += rows * 10 + 3; },
      table(headers, rows, opts = {}) { doc.autoTable(Object.assign({ head: [headers.map(pdfTxt)], body: rows.map((r) => r.map((c) => pdfTxt(c))), startY: ctx.y, margin: { top: TOP, bottom: 16, left: M, right: M }, styles: { fontSize: 7.8, cellPadding: 1.6, lineColor: [214, 220, 226], lineWidth: 0.1, textColor: [30, 40, 50] }, headStyles: { fillColor: [23, 33, 43], textColor: 255, fontStyle: 'bold' }, alternateRowStyles: { fillColor: [245, 247, 249] }, theme: 'grid' }, opts)); ctx.y = doc.lastAutoTable.finalY + 6; },
      async images(list, per = 4) { if (!list.length) return; const gap = 4; const w = (W - 2 * M - gap * (per - 1)) / per; const h = w * 0.75; for (let i = 0; i < list.length; i++) { if (i % per === 0) { ctx.ensure(h + 9); } const x = M + (i % per) * (w + gap); const yy = ctx.y; try { const j = await Reports.toJpeg(list[i].src); doc.addImage(j, 'JPEG', x, yy, w, h); } catch (e) { doc.setDrawColor(200); doc.rect(x, yy, w, h); } doc.setFontSize(7); doc.setTextColor(90, 100, 110); doc.setFont('helvetica', 'normal'); doc.text(doc.splitTextToSize(pdfTxt(list[i].cap || ''), w)[0] || '', x, yy + h + 3.5); if (i % per === per - 1 || i === list.length - 1) ctx.y += h + 8; } },
    };
    await build(ctx);
    const n = doc.getNumberOfPages();
    for (let p = 1; p <= n; p++) {
      doc.setPage(p); doc.setFillColor(23, 33, 43); doc.rect(0, 0, W, 22, 'F'); doc.setFillColor(242, 183, 5); doc.rect(M, 5, 12, 12, 'F'); doc.setTextColor(27, 27, 27); doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.text('5S', M + 6, 12.6, { align: 'center' });
      doc.setTextColor(255); doc.setFontSize(11); doc.text(pdfTxt(st.reportHeader || '5S MANAGEMENT SYSTEM'), M + 16, 12.6); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(195, 205, 214);
      doc.setTextColor(255); doc.setFont('helvetica', 'bold'); doc.setFontSize(11); doc.text(pdfTxt(title), W - M, 10, { align: 'right' }); doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(195, 205, 214); if (sub) doc.text(pdfTxt(sub), W - M, 15, { align: 'right' });
      doc.setDrawColor(214, 220, 226); doc.setLineWidth(0.2); doc.line(M, H - 11, W - M, H - 11); doc.setFontSize(7); doc.setTextColor(120, 130, 140);
      doc.text(pdfTxt(`Generated ${fmtDT(nowISO())} by ${App.user.name} (${App.user.id})`), M, H - 6.5); doc.text(`Page ${p} of ${n}`, W / 2, H - 6.5, { align: 'center' }); doc.text(pdfTxt(st.docVersion || 'Rev 1.0'), W - M, H - 6.5, { align: 'right' });
    }
    return this.save(filename, doc.output('arraybuffer'));
  },
};

const Reports = {
  async toJpeg(src) { const im = await UI.loadImg(src); const w = Math.min(900, im.naturalWidth || 480), h = Math.round(w * ((im.naturalHeight || 360) / (im.naturalWidth || 480))); const c = document.createElement('canvas'); c.width = w; c.height = h; const x = c.getContext('2d'); x.fillStyle = '#fff'; x.fillRect(0, 0, w, h); x.drawImage(im, 0, 0, w, h); return c.toDataURL('image/jpeg', 0.8); },
  woData(w) {
    const qs = Domain.questionsOf(w); const fs = Store.all('findings').filter((f) => f.woId === w.id); const acts = Store.all('actions').filter((a) => fs.some((f) => f.id === a.findingId)); const prev = Domain.prevAudit(w); const z = Domain.zone(w.zone) || {};
    return { qs, fs, acts, prev, z, info: [['Audit number', w.no], ['Audit date', fmtDate(Domain.auditDate(w))], ['Audit type', w.auditType], ['Zone', `${z.code} - ${z.name}`], ['Department', w.dept], ['APU / Plant', `${Domain.apuName(w.apu)} / ${Domain.plantName(w.plant)}`], ['Auditor', Domain.uname(w.auditor)], ['Zone Leader', Domain.uname(w.leader)], ['Checksheet', `${w.csName} v${w.csVersion}`], ['Start / end', `${fmtDT(w.startedAt)} - ${fmtDT(w.endedAt).slice(-5)}`], ['Duration', w.duration ? w.duration + ' min' : '-'], ['Status', Domain.woStatus(w)]] };
  },
  async auditPDF(w) {
    const d = Reports.woData(w); const b = Domain.band(w.score.overall.pct) || {};
    await Exporter.pdf(`5S-Audit-Report-${w.no}.pdf`, { title: 'AUDIT REPORT', sub: `${w.no} | ${Domain.plantName(w.plant)} / ${w.dept} / ${w.zone}`, orientation: 'portrait' }, async (c) => {
      c.heading('Audit information'); c.kv(d.info, 3);
      c.heading('Score summary'); c.table(['Category', 'Score', 'Maximum', 'Percentage'], FS.S_KEYS.map((s) => [`${s} - ${Domain.sName(s)}`, w.score[s].got, w.score[s].max, fmtPct(w.score[s].pct, 1)]).concat([['Overall', w.score.overall.got, w.score.overall.max, `${fmtPct(w.score.overall.pct, 1)} - ${b.label || ''}`]]), { didParseCell: (h) => { if (h.section === 'body' && h.row.index === 5) h.cell.styles.fontStyle = 'bold'; } });
      c.text(`Previous score: ${d.prev ? fmtPct(d.prev.score.overall.pct, 1) + ' (' + fmtDate(Domain.auditDate(d.prev)) + ')' : 'none'}${d.prev ? `   Improvement: ${round1(w.score.overall.pct - d.prev.score.overall.pct)} pts` : ''}   Findings: ${d.fs.length} (Critical ${d.fs.filter((f) => f.severity === 'Critical').length}, Major ${d.fs.filter((f) => f.severity === 'Major').length}, Minor ${d.fs.filter((f) => f.severity === 'Minor').length}, Observation ${d.fs.filter((f) => f.severity === 'Observation').length})`);
      c.heading('Findings'); c.table(['Finding ID', 'S', 'Question', 'Finding', 'Severity', 'Responsible', 'Due', 'Status'], d.fs.map((f) => [f.no, f.s, f.qid, f.desc, f.severity, Domain.uname(f.responsible), fmtDate(f.due), Domain.findSt(f)]), { columnStyles: { 3: { cellWidth: 55 } } });
      c.heading('Corrective actions'); c.table(['Action ID', 'Finding', 'Action', 'Responsible', 'Target', 'Status', 'Verified by'], d.acts.map((a) => [a.no, a.findingNo || '', a.desc, Domain.uname(a.responsible), fmtDate(a.revisedTarget || a.target), Domain.actStatus(a), a.verifiedBy ? Domain.uname(a.verifiedBy) + ' ' + fmtDate(a.verifiedAt) : '']), { columnStyles: { 2: { cellWidth: 60 } } });
      c.heading('Full checksheet'); c.table(['ID', 'Question', 'Response', 'Remark'], d.qs.filter((q) => q.active !== false).map((q) => { const r = (w.responses || {})[q.qid] || {}; return [q.qid, q.text, r.v === undefined || r.v === null ? '-' : (r.v === 'NA' ? 'N/A' : r.v) + ' ' + Exec.respLabel(q, r.v), r.remark || '']; }), { columnStyles: { 1: { cellWidth: 80 }, 3: { cellWidth: 55 } } });
      const photos = []; d.qs.forEach((q) => { const r = (w.responses || {})[q.qid] || {}; (r.photos || []).forEach((p) => photos.push({ src: p.thumb, cap: `${q.qid}${r.findingId ? ' / ' + ((Store.get('findings', r.findingId) || {}).no || '') : ''}`, ref: p })); });
      d.acts.forEach((a) => (a.evidence || []).forEach((p) => photos.push({ src: p.thumb, cap: `${a.no} completion`, ref: p })));
      if (photos.length) { c.heading('Photographs'); for (const p of photos) { try { p.src = await Store.photoFull(p.ref); } catch (e) {} } await c.images(photos.slice(0, 24), 4); }
      c.heading('Approvals'); c.table(['Level', 'Status', 'Name', 'Date', 'Remark'], [['Auditor', 'Submitted', Domain.uname(w.auditor), fmtDT(w.submittedAt), '']].concat((w.approvals || []).map((a) => [a.level, a.status, a.by ? Domain.uname(a.by) : '', a.at ? fmtDT(a.at) : '', a.remark || ''])));
      c.ensure(26); const cw = (c.W - 2 * c.M) / 3; ['Auditor', 'Zone Leader', '5S Facilitator'].forEach((l, i) => { const x = c.M + i * cw; c.doc.setDrawColor(120); c.doc.line(x, c.y + 14, x + cw - 8, c.y + 14); c.doc.setFontSize(8); c.doc.setTextColor(90); c.doc.text(l, x, c.y + 18); }); c.y += 22;
    });
    Domain.log('Reports', w.no, 'Audit report exported (PDF)');
  },
  async auditXLSX(w) {
    const d = Reports.woData(w);
    await Exporter.xlsx(`5S-Audit-Report-${w.no}.xlsx`, [
      { name: 'Summary', title: 'Audit Report ' + w.no, kv: d.info, headers: ['Category', 'Score', 'Maximum', 'Percentage'], rows: FS.S_KEYS.map((s) => [`${s} - ${Domain.sName(s)}`, w.score[s].got, w.score[s].max, w.score[s].pct]).concat([['Overall', w.score.overall.got, w.score.overall.max, w.score.overall.pct]]) },
      { name: 'Checksheet', title: 'Checksheet responses', headers: ['ID', 'S', 'Question', 'Response', 'Rating', 'Remark', 'Photos', 'Finding'], rows: d.qs.map((q) => { const r = (w.responses || {})[q.qid] || {}; return [q.qid, q.s, q.text, r.v ?? '', Exec.respLabel(q, r.v), r.remark || '', (r.photos || []).length, r.findingId ? (Store.get('findings', r.findingId) || {}).no : '']; }) },
      { name: 'Findings', title: 'Findings', headers: ['Finding ID', 'S', 'Question', 'Finding', 'Category', 'Severity', 'Responsible', 'Due', 'Status'], rows: d.fs.map((f) => [f.no, f.s, f.qid, f.desc, f.category, f.severity, Domain.uname(f.responsible), f.due, Domain.findSt(f)]) },
      { name: 'Actions', title: 'Corrective actions', headers: ['Action ID', 'Finding', 'Action', 'Type', 'Responsible', 'Target', 'Status', 'Completed', 'Verified by', 'Verified on'], rows: d.acts.map((a) => [a.no, a.findingNo, a.desc, a.type, Domain.uname(a.responsible), a.revisedTarget || a.target, Domain.actStatus(a), a.completedAt || '', a.verifiedBy ? Domain.uname(a.verifiedBy) : '', (a.verifiedAt || '').slice(0, 10)]) },
    ]);
    Domain.log('Reports', w.no, 'Audit report exported (Excel)');
  },
  async scorecardPDF(w) {
    const d = Reports.woData(w); const b = Domain.band(w.score.overall.pct) || {}; const hex = (h) => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16)];
    await Exporter.pdf(`5S-Scorecard-${w.no}.pdf`, { title: '5S AUDIT SCORECARD', sub: w.no, orientation: 'portrait' }, async (c) => {
      const doc = c.doc; c.kv([['Zone', `${d.z.code} - ${d.z.name}`], ['Department', w.dept], ['Audit date', fmtDate(Domain.auditDate(w))], ['Auditor', Domain.uname(w.auditor)], ['APU', Domain.apuName(w.apu)], ['Audit type', w.auditType]], 3);
      c.ensure(60); doc.setFillColor(...hex(b.color || '#1d5d90')); doc.roundedRect(c.M, c.y, c.W - 2 * c.M, 24, 2, 2, 'F'); doc.setTextColor(255); doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.text('OVERALL SCORE', c.M + 6, c.y + 8); doc.setFontSize(22); doc.text(pdfTxt(`${fmtPct(w.score.overall.pct)} - ${(b.label || '').toUpperCase()}`), c.M + 6, c.y + 19); c.y += 32;
      FS.S_KEYS.forEach((s, i) => { const p = w.score[s].pct || 0; const y = c.y + i * 9; doc.setTextColor(30); doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.text(`${s}  ${pdfTxt(Domain.sName(s))}`, c.M, y + 4); doc.setFillColor(232, 236, 240); doc.rect(c.M + 50, y, 100, 5, 'F'); doc.setFillColor(...hex(Domain.bandColor(p).startsWith('#') ? Domain.bandColor(p) : '#1d5d90')); doc.rect(c.M + 50, y, p, 5, 'F'); doc.text(fmtPct(p), c.M + 156, y + 4); }); c.y += 50;
      c.table(['Findings', 'Critical', 'Major', 'Minor', 'Observation', 'Open actions', 'Closed actions'], [[d.fs.length, d.fs.filter((f) => f.severity === 'Critical').length, d.fs.filter((f) => f.severity === 'Major').length, d.fs.filter((f) => f.severity === 'Minor').length, d.fs.filter((f) => f.severity === 'Observation').length, d.acts.filter((a) => Domain.isActOpen(a)).length, d.acts.filter((a) => !Domain.isActOpen(a)).length]]);
      c.heading('Approval / sign-off'); c.ensure(30); const cw = (c.W - 2 * c.M) / 3; const ap = (l) => (w.approvals || []).find((a) => a.level === l && a.status === 'Approved');
      [['Auditor', w.auditor, w.submittedAt], ['Zone Leader', (ap('Zone Leader') || {}).by, (ap('Zone Leader') || {}).at], ['5S Facilitator', (ap('5S Facilitator') || {}).by, (ap('5S Facilitator') || {}).at]].forEach(([l, id, at], i) => { const x = c.M + i * cw; doc.setFontSize(9); doc.setTextColor(30); doc.setFont('helvetica', 'bold'); doc.text(pdfTxt(id ? Domain.uname(id) : ''), x, c.y + 10); doc.setFont('helvetica', 'normal'); doc.setFontSize(7.5); doc.setTextColor(110); doc.text(at ? 'Signed ' + fmtDate(at) : 'Pending', x, c.y + 14); doc.setDrawColor(120); doc.line(x, c.y + 16, x + cw - 8, c.y + 16); doc.text(l, x, c.y + 20); }); c.y += 26;
    });
    Domain.log('Reports', w.no, 'Scorecard exported (PDF)');
  },
  /* tabular report catalogue */
  defs: {
    mgmt: { t: 'Management Summary Report', d: 'KPIs, APU and department ranking, risk zones and recurring issues' },
    zone: { t: 'Zone Performance Report', d: 'Latest S1–S5 scores per zone, or one zone’s audit history', zone: true },
    dept: { t: 'Department Performance Report', d: 'Completion, scores and action closure by department' },
    monthly: { t: 'Monthly 5S Report', d: 'All audits in the selected month with scores and findings' },
    annual: { t: 'Annual 5S Report', d: 'Zone × month overall-score matrix for the financial year' },
    pending: { t: 'Action Pending Report', d: 'Every open corrective action with owner and target' },
    overdue: { t: 'Overdue Action Report', d: 'Actions past their target date, with days overdue' },
    repeat: { t: 'Repeat Finding Report', d: 'Checkpoints failing in more than one audit of a zone' },
    auditor: { t: 'Auditor Performance Report', d: 'Audits, on-time %, duration and findings per auditor' },
    trend: { t: '5S Score Trend Report', d: 'Monthly S1–S5 and overall averages' },
    findings: { t: 'Findings Register', d: 'All findings with severity, owner and status' },
    kaizen: { t: 'Improvement / Kaizen Report', d: 'Improvements with benefits and savings' },
    audit: { t: 'Audit Report & Scorecard', d: 'Full report for one audit: checksheet, findings, photos, actions', wo: true },
  },
  build(key, s) {
    const f = Filt.toFilter(s); const per = Filt.label(s); const scope = `${App.plant === 'all' ? 'All plants' : Domain.plantName(App.plant)}${s.apu ? ' / ' + Domain.apuName(s.apu) : ''}${s.dept ? ' / ' + s.dept : ''}${s.zone ? ' / ' + s.zone : ''}`;
    const sub = `${scope} | ${per}`; const R = { sub, sections: [], kv: null };
    const done = () => Domain.completedWOs(f);
    if (key === 'mgmt') { const k = Domain.kpis(f); R.kv = [['Audits planned', k.planned], ['Audits completed', k.completed], ['Completion %', fmtPct(k.completion)], ['Average 5S score', fmtPct(k.avgScore, 1)], ['Findings', k.findings], ['Open findings', k.findingsOpen], ['Closed findings', k.findingsClosed], ['Critical findings', k.critical], ['Open actions', k.openActions], ['Overdue actions', k.overdue], ['Action closure %', fmtPct(k.actionClosure)], ['Finding rate / audit', k.findingRate === null ? '-' : k.findingRate.toFixed(2)], ['Repeat finding rate', fmtPct(k.repeatRate)], ['Best zone', k.best ? `${k.best.z.code} ${fmtPct(k.best.pct)}` : '-'], ['Lowest zone', k.worst ? `${k.worst.z.code} ${fmtPct(k.worst.pct)}` : '-']];
      R.sections.push({ h: 'APU ranking', headers: ['Rank', 'APU', 'Plant', 'Audits', 'Average score', 'Rating'], rows: Object.entries(groupBy(k.done, (w) => w.apu)).map(([a, l]) => [a, l, avg(l.map((w) => w.score.overall.pct))]).sort((x, y) => y[2] - x[2]).map(([a, l, v], i) => [i + 1, Domain.apuName(a), Domain.plantName((Domain.apu(a) || {}).plant), l.length, round1(v), (Domain.band(v) || {}).label]) });
      R.sections.push({ h: 'S1–S5 performance', headers: ['S', 'Name', 'Average %'], rows: FS.S_KEYS.map((x) => [x, Domain.sName(x), Domain.sAverages(k.done)[x]]) });
      R.sections.push({ h: 'Zones needing attention (lowest 8)', headers: ['Zone', 'Name', 'Department', 'Latest score', 'Open actions', 'Overdue'], rows: k.zScores.slice(-8).reverse().map((x) => [x.z.code, x.z.name, x.z.dept, round1(x.pct), Domain.zoneOpenActions(x.z.id).length, Domain.zoneOpenActions(x.z.id).filter((a) => Domain.actStatus(a) === 'Overdue').length]) });
      R.sections.push({ h: 'Top recurring findings', headers: ['S', 'Finding', 'Occurrences', 'Zones'], rows: Domain.recurringThemes(k.fs).slice(0, 8).map((t) => [t.s, t.label, t.n, t.zones.join(', ')]) });
      R.sections.push({ h: 'Alerts', headers: ['Level', 'Alert'], rows: Domain.alerts(f).slice(0, 15).map((a) => [{ crit: 'Critical', warn: 'Warning', info: 'Info' }[a.lvl], a.text]) }); }
    if (key === 'zone') { if (s.zone) { const l = Store.all('workorders').filter((w) => w.zone === s.zone && Domain.isDone(w) && w.score).sort((a, b) => Domain.auditDate(a).localeCompare(Domain.auditDate(b))); const z = Domain.zone(s.zone); R.kv = [['Zone', `${z.code} - ${z.name}`], ['Department', z.dept], ['APU', Domain.apuName(z.apu)], ['Zone Leader', Domain.uname(z.leader)], ['Members', (z.members || []).length], ['Audits', l.length]]; R.sections.push({ h: 'Audit history', headers: ['Audit no.', 'Date', 'Type', 'Auditor', 'S1', 'S2', 'S3', 'S4', 'S5', 'Overall', 'Findings'], rows: l.map((w) => [w.no, Domain.auditDate(w), w.auditType, Domain.uname(w.auditor)].concat(FS.S_KEYS.map((x) => round1(w.score[x].pct)), [round1(w.score.overall.pct), Store.all('findings').filter((x) => x.woId === w.id).length])) }); }
      else { const d = done(); R.sections.push({ h: 'Zone performance (latest audit in period)', headers: ['Zone', 'Name', 'APU', 'Department', 'S1', 'S2', 'S3', 'S4', 'S5', 'Overall', 'Rating', 'Audits', 'Open actions'], rows: Domain.scopeZones().filter((z) => (!s.apu || z.apu === s.apu) && (!s.dept || z.dept === s.dept)).map((z) => { const l = d.filter((w) => w.zone === z.id).sort((a, b) => Domain.auditDate(b).localeCompare(Domain.auditDate(a))); const w = l[0]; return [z.code, z.name, Domain.apuName(z.apu), z.dept].concat(FS.S_KEYS.map((x) => (w ? round1(w.score[x].pct) : '')), [w ? round1(w.score.overall.pct) : '', w ? (Domain.band(w.score.overall.pct) || {}).label : '', l.length, Domain.zoneOpenActions(z.id).length]); }).sort((a, b) => (b[9] || 0) - (a[9] || 0)) }); } }
    if (key === 'dept') { const all = Domain.applyFilter(Domain.wos().filter((w) => w.status !== 'Cancelled'), f, 'wo'); const acts = Domain.applyFilter(Domain.actions(), f, 'action'); const fs = Domain.applyFilter(Domain.findings(), f, 'finding'); R.sections.push({ h: 'Department performance', headers: ['Department', 'Zones', 'Planned', 'Completed', 'Completion %', 'Average score', 'Findings', 'Actions', 'Closure %', 'Overdue'], rows: Object.entries(groupBy(all, (w) => w.dept)).map(([d, l]) => { const dn = l.filter((w) => Domain.isDone(w)); const a = acts.filter((x) => x.dept === d); return [d, uniq(l.map((w) => w.zone)).length, l.length, dn.length, round1((dn.length / l.length) * 100), round1(avg(dn.map((w) => w.score && w.score.overall.pct))), fs.filter((x) => x.dept === d).length, a.length, a.length ? round1((a.filter((x) => !Domain.isActOpen(x)).length / a.length) * 100) : '', a.filter((x) => Domain.actStatus(x) === 'Overdue').length]; }).sort((a, b) => (b[5] || 0) - (a[5] || 0)) }); }
    if (key === 'monthly') { const all = Domain.applyFilter(Domain.wos().filter((w) => w.status !== 'Cancelled'), f, 'wo'); const k = Domain.kpis(f); R.kv = [['Planned', k.planned], ['Completed', k.completed], ['Completion', fmtPct(k.completion)], ['Average score', fmtPct(k.avgScore, 1)], ['Findings', k.findings], ['Overdue actions', k.overdue]]; R.sections.push({ h: 'Audits', headers: ['Audit no.', 'Zone', 'Planned', 'Audited', 'Auditor', 'Status', 'S1', 'S2', 'S3', 'S4', 'S5', 'Overall', 'Findings'], rows: all.sort((a, b) => a.plannedDate.localeCompare(b.plannedDate)).map((w) => [w.no, w.zone, w.plannedDate, Domain.isDone(w) ? Domain.auditDate(w) : '', Domain.uname(w.auditor), Domain.woStatus(w)].concat(FS.S_KEYS.map((x) => (w.score && Domain.isDone(w) ? round1(w.score[x].pct) : '')), [w.score && Domain.isDone(w) ? round1(w.score.overall.pct) : '', Store.all('findings').filter((x) => x.woId === w.id).length])) }); }
    if (key === 'annual') { const fy = s.ptype === 'year' ? s.pval : String(FS.fiscalYear(Domain.today, Domain.settings().fiscalYearStart || 4)); const months = Domain.fyMonths(fy + '-' + FS.pad(Domain.settings().fiscalYearStart || 4)); R.sub = `${scope} | FY ${fy}-${String(Number(fy) + 1).slice(2)}`; const d = Domain.completedWOs(Object.assign({}, f, { period: { type: 'year', value: fy } })); R.sections.push({ h: 'Overall score by zone and month', headers: ['Zone', 'Name'].concat(months.map((m) => MON[Number(m.slice(5)) - 1]), ['Average']), rows: Domain.scopeZones().filter((z) => (!s.apu || z.apu === s.apu) && (!s.dept || z.dept === s.dept)).map((z) => { const v = months.map((m) => round1(avg(d.filter((w) => w.zone === z.id && Domain.auditDate(w).startsWith(m)).map((w) => w.score.overall.pct)))); return [z.code, z.name].concat(v.map((x) => (x === null ? '' : x)), [round1(avg(v))]); }) }); }
    if (key === 'pending' || key === 'overdue') { const list = Domain.applyFilter(Domain.actions(), Object.assign({}, f, { period: { type: 'all' } }), 'action').filter((a) => Domain.isActOpen(a) && (key === 'pending' || Domain.actStatus(a) === 'Overdue')); R.sub = scope + ' | as of ' + fmtDate(Domain.today); R.sections.push({ h: key === 'pending' ? 'Pending actions' : 'Overdue actions', headers: ['Action ID', 'Finding', 'Zone', 'Severity', 'Action', 'Responsible', 'Department', 'Target', 'Status'].concat(key === 'overdue' ? ['Days overdue'] : ['Age (days)']), rows: list.sort((a, b) => (a.revisedTarget || a.target).localeCompare(b.revisedTarget || b.target)).map((a) => [a.no, a.findingNo || '', a.zone, (Store.get('findings', a.findingId) || {}).severity || '', a.desc, Domain.uname(a.responsible), a.dept, a.revisedTarget || a.target, Domain.actStatus(a), key === 'overdue' ? -FS.diffDays(a.revisedTarget || a.target, Domain.today) : FS.diffDays(Domain.today, a.createdAt.slice(0, 10))]) }); }
    if (key === 'repeat') { R.sub = scope; R.sections.push({ h: 'Repeat findings', headers: ['Zone', 'S', 'Question', 'Latest finding', 'Occurrences', 'Consecutive', 'First', 'Last', 'Responsible', 'Previous action', 'Effectiveness'], rows: Domain.repeatGroups(Domain.applyFilter(Domain.findings(), Object.assign({}, f, { period: { type: 'all' } }), 'finding')).map((r) => [r.zone, r.s, r.qid, r.desc, r.count, r.consecutive, r.first, r.last, Domain.uname(r.responsible), r.prevAction, r.effectiveness]) }); }
    if (key === 'auditor') { const all = Domain.applyFilter(Domain.wos().filter((w) => w.status !== 'Cancelled'), f, 'wo'); R.sections.push({ h: 'Auditor performance', headers: ['Auditor', 'Assigned', 'Completed', 'Overdue', 'On-time %', 'Avg duration (min)', 'Findings', 'Findings / audit', 'Avg score'], rows: Object.entries(groupBy(all, (w) => w.auditor)).map(([a, l]) => { const dn = l.filter((w) => Domain.isDone(w)); const fs = Store.all('findings').filter((x) => dn.some((w) => w.id === x.woId)); return [Domain.uname(a), l.length, dn.length, l.filter((w) => Domain.woStatus(w) === 'Overdue').length, dn.length ? round1((dn.filter((w) => Domain.auditDate(w) <= w.dueDate).length / dn.length) * 100) : '', round1(avg(dn.map((w) => w.duration))), fs.length, dn.length ? round1(fs.length / dn.length) : '', round1(avg(dn.map((w) => w.score && w.score.overall.pct)))]; }) }); }
    if (key === 'trend') { const months = Domain.fyMonths(s.ptype === 'month' ? s.pval : Domain.lastDataMonth()).filter((m) => m <= Domain.today.slice(0, 7)); const tr = Domain.monthlyTrend(Object.assign({}, f, { period: { type: 'all' } }), months); R.sections.push({ h: 'Monthly 5S score trend', headers: ['Month', 'S1', 'S2', 'S3', 'S4', 'S5', 'Overall', 'Audits', 'Change vs previous'], rows: tr.map((t, i) => [fmtMonth(t.m)].concat(FS.S_KEYS.map((x) => t[x] ?? ''), [t.overall ?? '', t.n, i && t.overall !== null && tr[i - 1].overall !== null ? round1(t.overall - tr[i - 1].overall) : ''])) }); }
    if (key === 'findings') { R.sections.push({ h: 'Findings', headers: ['Finding ID', 'Audit', 'Zone', 'S', 'Question', 'Finding', 'Category', 'Severity', 'Responsible', 'Raised', 'Due', 'Status'], rows: Domain.applyFilter(Domain.findings(), f, 'finding').sort((a, b) => (b.auditDate || '').localeCompare(a.auditDate || '')).map((x) => [x.no, x.woNo, x.zone, x.s, x.qid, x.desc, x.category, x.severity, Domain.uname(x.responsible), x.auditDate, x.due, Domain.findSt(x)]) }); }
    if (key === 'kaizen') { const l = Store.all('improvements').filter((i) => Domain.inScope(i)); R.kv = [['Improvements', l.length], ['Total saving (Rs.)', sum(l.map((i) => i.saving)).toLocaleString('en-IN')]]; R.sections.push({ h: 'Improvements', headers: ['ID', 'Zone', 'S', 'Title', 'Before', 'After', 'Benefits', 'Saving (Rs.)', 'Owner', 'Date', 'Status'], rows: l.map((i) => [i.no, i.zone, i.s || '', i.title, i.before, i.after, (i.benefits || []).join(', '), i.saving || 0, Domain.uname(i.owner), i.date, i.status]) }); }
    return R;
  },
};

Pages.reports = {
  perm: 'Reports',
  render(p) {
    if (p.r) { App.ui.repKey = p.r; if (p.zone) App.st('rep', Filt.defaults()).zone = p.zone; delete p.r; delete p.zone; }
    const key = App.ui.repKey || 'mgmt'; const def = Reports.defs[key]; const s = App.st('rep', Filt.defaults());
    const limited = Domain.perm('Reports') === 'limited'; const allowed = limited ? ['pending', 'overdue', 'findings', 'kaizen'] : Object.keys(Reports.defs);
    const list = `<div class="stack tight">${Object.entries(Reports.defs).filter(([k]) => allowed.includes(k)).map(([k, d]) => `<button class="btn ${k === key ? 'primary' : 'ghost'}" style="justify-content:flex-start;height:auto;padding:9px 12px;white-space:normal;text-align:left" data-act="tab" data-key="repKey" data-v="${k}"><span><b>${esc(d.t)}</b><br><span class="small" style="opacity:.8;font-weight:400">${esc(d.d)}</span></span></button>`).join('')}</div>`;
    let body = '';
    if (def.wo) {
      const done = Domain.wos().filter((w) => Domain.isDone(w) && w.score).sort((a, b) => Domain.auditDate(b).localeCompare(Domain.auditDate(a)));
      const sel = App.ui.repWo || (done[0] && done[0].id);
      body = `<div class="filters"><select data-filter="repWo" style="max-width:420px" aria-label="Audit">${done.map((w) => `<option value="${w.id}" ${w.id === sel ? 'selected' : ''}>${esc(w.no)} · ${esc(w.zone)} · ${fmtDate(Domain.auditDate(w))} · ${Math.round(w.score.overall.pct)}%</option>`).join('')}</select></div>${sel ? `<div class="row"><button class="btn primary" data-act="rep-audit-pdf" data-id="${sel}">${icon('download')}Audit report (PDF)</button><button class="btn" data-act="rep-audit-xlsx" data-id="${sel}">${icon('download')}Audit report (Excel)</button><button class="btn" data-act="rep-score-pdf" data-id="${sel}">${icon('award')}Scorecard (PDF)</button><button class="btn ghost" data-go="wo" data-id="${sel}">Open audit summary</button></div><div class="small muted" style="margin-top:10px">The audit report includes audit details, organisation and zone, the full checksheet with responses, S1–S5 scores, findings, photographs, corrective actions and approvals.</div>` : UI.empty('file', 'No submitted audits in your scope yet')}`;
    } else {
      const R = Reports.build(key, s);
      body = `${Filt.bar('rep', s, { auditor: false })}<div class="row" style="margin-bottom:12px"><button class="btn primary" data-act="rep-pdf">${icon('download')}PDF</button><button class="btn" data-act="rep-xlsx">${icon('download')}Excel</button><button class="btn" data-act="rep-csv">${icon('download')}CSV</button><span class="small muted">${esc(R.sub)}</span></div>
        ${R.kv ? `<div class="panel" style="margin-bottom:14px">${UI.kv(R.kv.map(([k, v]) => [k, esc(v)]))}</div>` : ''}
        ${R.sections.map((sec) => `<h3 style="margin:14px 0 8px">${esc(sec.h)} <span class="small faint">(${sec.rows.length})</span></h3>${sec.rows.length ? `<div class="tbl-wrap" style="max-height:480px"><table class="tbl"><thead><tr>${sec.headers.map((h) => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${sec.rows.slice(0, 300).map((r) => `<tr>${r.map((c) => `<td class="${typeof c === 'number' ? 'num' : ''}">${esc(c ?? '')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${sec.rows.length > 300 ? `<div class="small faint">Preview shows 300 of ${sec.rows.length} rows; exports include all rows.</div>` : ''}` : '<div class="small faint">No rows for this selection.</div>'}`).join('')}`;
    }
    return `${UI.head('Reports', [], '', 'Downloadable reports in PDF, Excel and CSV with a standard manufacturing header and footer')}<div class="grid"><div class="c3" style="grid-column:span 3">${list}</div><div class="c8" style="grid-column:span 9">${UI.card(esc(def.t), body)}</div></div>`;
  },
};
Object.assign(Acts, {
  async 'rep-audit-pdf'(el) { UI.toast('Preparing PDF…'); await Reports.auditPDF(Store.get('workorders', el.dataset.id)); },
  async 'rep-audit-xlsx'(el) { UI.toast('Preparing Excel…'); await Reports.auditXLSX(Store.get('workorders', el.dataset.id)); },
  async 'rep-score-pdf'(el) { UI.toast('Preparing scorecard…'); await Reports.scorecardPDF(Store.get('workorders', el.dataset.id)); },
  async 'rep-pdf'() { const key = App.ui.repKey || 'mgmt'; const d = Reports.defs[key]; const R = Reports.build(key, App.st('rep', Filt.defaults())); UI.toast('Preparing PDF…'); await Exporter.pdf(`${d.t.replace(/[^\w]+/g, '-')}.pdf`, { title: d.t.toUpperCase(), sub: R.sub }, async (c) => { if (R.kv) { c.heading('Key figures'); c.kv(R.kv.map(([k, v]) => [k, String(v)]), 5); } R.sections.forEach((sec) => { c.heading(sec.h); c.table(sec.headers, sec.rows); }); }); Domain.log('Reports', d.t, 'Report exported (PDF)', '', R.sub); },
  async 'rep-xlsx'() { const key = App.ui.repKey || 'mgmt'; const d = Reports.defs[key]; const R = Reports.build(key, App.st('rep', Filt.defaults())); await Exporter.xlsx(`${d.t.replace(/[^\w]+/g, '-')}.xlsx`, R.sections.map((sec, i) => ({ name: sec.h, title: d.t + ' – ' + sec.h, sub: R.sub, kv: i === 0 && R.kv ? R.kv : null, headers: sec.headers, rows: sec.rows }))); Domain.log('Reports', d.t, 'Report exported (Excel)', '', R.sub); },
  async 'rep-csv'() { const key = App.ui.repKey || 'mgmt'; const d = Reports.defs[key]; const R = Reports.build(key, App.st('rep', Filt.defaults())); const sec = R.sections[R.sections.length > 1 && key === 'mgmt' ? 0 : 0]; await Exporter.csv(`${d.t.replace(/[^\w]+/g, '-')}.csv`, sec.headers, sec.rows); Domain.log('Reports', d.t, 'Report exported (CSV)', '', R.sub); },
});
